### PR TITLE
Add fsnotify to monitor the configMap path

### PR DESCRIPTION
**Pull request by lubronzhan**
Fix https://github.com/projectcontour/contour/issues/2491

Add file system notifier to monitor the path to which the confgMap of contour deployment is mounted. So that if user updates the contour's ConfigMap, the contour deployment will be restarted

TODO:
- [x]  E2E test

### CODE REVIEW

**Comment by lubronzhan** [comment]
I tried Unit test, but there are many events triggered on MACOS due to indexing

Pipeline: https://github.com/projectcontour/contour/actions/runs/7947356518/job/21696092887?pr=6196

Known issue [here](https://github.com/fsnotify/fsnotify/issues/600) 


It also seems to happen on ubuntu https://github.com/projectcontour/contour/actions/runs/7947356518/job/21696093042?pr=6196

So I didn't do unit test, but e2e test could pass successfully. log in contour
```
time="2024-02-18T01:36:27Z" level=fatal msg="restarting contour because received event CREATE on file /config\n" context=fsnotify-watcher
```

**Comment by tsaarni** [comment]
Looks good in general but few remarks:

* It would be nice to have either opt-in or opt-out for automatic restart. Restart can cause undefined behavior in certain scenarios. For example when the ConfigMap is part of Contour helm chart / manifest, then upgrade itself can trigger restart of all Contours at once. Old version of Contour would attempt to read the new version of the configuration file which it might be unable to parse due to newly added fields, and pod could to go into crash loop.
* The configuration file path is not necessarily guaranteed to be `/config` since it is given on command line `-c/--config-path` (though it is of course `/config` for those using the example manifests)

**Review by sunjayBhatia — COMMENTED** [review]
Sorry for not publicizing this issue more but we have this plan as well: https://github.com/projectcontour/contour/issues/6159 which this PR might be at odds with (i.e. might be ripped out if we deprecate/remove the support for the ConfigMap)

**Comment by lubronzhan** [comment]
Thank you all for the comments. Yeah if we are moving away, let me close it as https://github.com/projectcontour/contour/issues/6159 is taking precedence.

**Pull request closed without merging**
