### PR TITLE
(release 1-14) Cherrypick #3834

### PR DESCRIPTION
**Pull request by stevesloka**
Move to Envoy Admin over unix socket to mitigate security issues with external name services.

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
@stevesloka I know the E2E stuff didn't cherry-pick cleanly, what about the rest of the code? Any files to focus on for review?

**Comment by stevesloka** [comment]
@skriss there are a couple places that are the main bits to look at:

1. Bootstrap to use the socket instead of an ip address
2. Shutdown manager uses socket mapped through volume
3. Static listener gets created in Contour xDS to expose read-only endpoints in Envoy
4. Example yaml changes to use the socket & volumes

**Review by skriss — APPROVED** [review]
LGTM (looked at the diffs of all non-test files compared to #3934)

**Comment by sunjayBhatia** [comment]
One issue is that on this branch, the manifests have contour image tag v1.14.1, had to manually change that locally to actually test the image in this pr

**Comment by sunjayBhatia** [comment]
made a PR for debugging: https://github.com/projectcontour/contour/pull/3971

**Comment by skriss** [comment]
FYI saw what I think are the same CI issues in my Envoy PRs against release-1.15 and release-1.14: https://github.com/projectcontour/contour/pull/3969/checks?check_run_id=3416335030 and https://github.com/projectcontour/contour/pull/3970/checks?check_run_id=3416341477

**Review by youngnick — APPROVED** [review]
This LGTM, let's wait for a report from @sunjayBhatia as to if there are any fixes for the CI failures before merging though.

**Comment by skriss** [comment]
Alright, CI issues have been fixed on this branch and this is all green 🎉

**Pull request merged**
