### PR TITLE
Add kustomization.yaml

### PR DESCRIPTION
**Pull request by alex1989hu**
This will add a kustomization.yaml file, to let users use kustomize.

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

### CODE REVIEW

**Comment by jpeach** [comment]
xref #2088

**Comment by davecheney** [comment]
Thank you for this change. I don't think this is right,

`examples/render` is for generated files, please don't add something manually to that directory. Also how will this file be used? We don't recommend people use `k apply -f examples/render`, instead the output of the render process is bounced through the projectcontour.io website.

**Comment by alex1989hu** [comment]
@davecheney
I know that directory contains two rendered files. Unfortunately, the master branch does not contain render.sh - that is why I was not able to modify it to exclude any file during listing of `examples/contour/*.yaml`. I think this directory is okay, but I would like to clearly see how it is working. I need some clarification. Could you describe how does website bounce/render yaml files? Which yaml files are being read during this bounce/render? I am also interested how does website render it?

**Comment by davecheney** [comment]
Please log a bug for the missing render.sh

The redirection magic is in site/_redirects

On 17 Feb 2020, at 08:53, Alex SZAKALY <notifications@github.com> wrote:

﻿

@davecheney<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavecheney&data=02%7C01%7Ccheneyd%40vmware.com%7Cdbe8e6f21d2b4de80e9f08d7b32ab15a%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637174868276030421&sdata=lr9wYj7FgrMfcoiYvthAhnifInEfmaVtOCfOfnP2KJE%3D&reserved=0>
I know that directory contains two rendered files. Unfortunately, the master branch does not contain render.sh - that is why I was not able to modify it to exclude any file during listing of examples/contour/*.yaml. I think this directory is okay, but I would like to clearly see how it is working. I need some clarification. Could you describe how does website bounce/render yaml files? Which yaml files are being read during this bounce/render? I am also interested how does website render it?

**Comment by jpeach** [comment]
> On 17 Feb 2020, at 8:53 am, Alex SZAKALY <notifications@github.com> wrote:
> 
> I know that directory contains two rendered files. Unfortunately, the master branch does not contain render.sh

That script was moved to ./hack/generate-deployment.sh as part of consolidating all the code/doc/yaml generation scripts.

**Comment by jpeach** [comment]
> On 17 Feb 2020, at 8:55 am, Dave Cheney <notifications@github.com> wrote:
> 
> Please log a bug for the missing render.sh 
> 
> The redirection magic is in site/_redirects 

Huh. I thought that the redirect was at the directory, in which case kustomize would see the kustomization.yaml and it wold be a remote base.

:(

**Comment by davecheney** [comment]
I hoped that netlify redirects worked that way, but I think I tried and it didn’t work.

**Comment by alex1989hu** [comment]
@davecheney: Do you have any proposal? My idea:
- Optioan A: modify the script to write those 2 lines 
- Option B: move file into examples directory to and list all manifest in contour directory.  

I am little bit confused now. Your HTTP 302 points the same rendered file as l pointed in this PR. I am glad to modify it once we found the ideal solution

**Comment by davecheney** [comment]
I’m afraid I don’t have any experience with kustomize so can only speak extemporaniously.

**Comment by jpeach** [comment]
@alex1989hu Can kustomize consume `https://projectcontour.io/quickstart/contour.yaml` as a base? If we add a redirect for `https://projectcontour.io/quickstart/kustomization.yaml`, does it work?

**Comment by alex1989hu** [comment]
> @alex1989hu Can kustomize consume `https://projectcontour.io/quickstart/contour.yaml` as a base? If we add a redirect for `https://projectcontour.io/quickstart/kustomization.yaml`, does it work?

Currently not, but kindly ask you to check this **PR:** https://github.com/kubernetes-sigs/kustomize/pull/2167

**Comment by jpeach** [comment]
'kk. Well, I'm happy to either leave this as is or revert it. Either way, I'd like to see more extensive kustomize support and would be happy to shepherd that work.

**Pull request merged**
