### PR TITLE
[WIP] Attempt at fixing knative-sandbox/net-contour#226

### PR DESCRIPTION
**Pull request by mattmoor**
At this point, I just wanted to push my WIP changes that I've been discussing in slack.

This is against `release-1.8` as I've been dropping my binaries into https://github.com/knative/serving/pull/9214 for testing.

Related: https://github.com/knative-sandbox/net-contour/issues/226

### CODE REVIEW

**Comment by youngnick** [comment]
The change to patch for status updates looks good, but most of the changes by volume seem to be about changing to `metav1.Object`. I don't dispute we need to do that at some point, but is it required for this change? I couldn't see if it was on a quick look.

**Comment by mattmoor** [comment]
@youngnick It was just an itch I started to scratch as I was looking at passing the `metav1.Object` through `StatusUpdate`.  I am sure we could get away without it even locally if we tried, and certainly don't need the volume of changes I made here.

While it might make sense to do a similar refactor at HEAD, I think the churn is inappropriate for a cherry-pick anyways.  Sorry for the extra noise 😅 

It looks like the `Patch()` version passed our CI.  I'm gonna run it a few more times and look at the latency data today, and (assuming nothing explodes or is amiss) will try to get a cleaned up version of the change ready for review today 🤞

**Comment by mattmoor** [comment]
I've opened https://github.com/projectcontour/contour/issues/2857 to track the balance of the (potential) performance win to be had by eliminating status updates.  I doubt we can close this gap completely, but I'd wager we can get pretty close.

**Comment by mattmoor** [comment]
I am going to close this for now, and reopen this as a proper cherry-pick of https://github.com/projectcontour/contour/pull/2854 once it has landed.

**Pull request closed without merging**
