### PR TITLE
site: Update gateway-api guide

### PR DESCRIPTION
**Pull request by stevesloka**
Updates the guide to show how to run sample gateway-apis resources without the operator.

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by youngnick** [comment]
Hold #3464 and #3465 until we have more consensus that this is the direction we want to go with.

**Comment by stevesloka** [comment]
I still think option is relevant (non-operator). I'll write up a controller in my own time to update status on the Gateway to allow this implementation.

**Comment by skriss** [comment]
I do think Contour should support this mode, and I think we should talk about it in terms of "static" vs. "dynamic" provisioning of the Gateway. You can deploy Contour+Envoy manually to statically provision, or you can use the operator/Gateway controller to dynamically provision. There are different tradeoffs for each.

**Comment by youngnick** [comment]
The static vs dynamic distinction makes sense to me, but I don't understand the point of having a controller that will "reconcile" Gateways, but not update the Contour and Envoy deployment when changes are made. In my book, that is not reconciliation.

**Pull request closed without merging**
