### PR TITLE
chore: remove description column of httpproxy

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>

fixes https://github.com/projectcontour/contour/issues/2978

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
LGTM, thanks @kushthedude.

**Comment by stevesloka** [comment]
Is there a way to show all the errors in the field instead of the current static message as James suggested (
https://github.com/projectcontour/contour/issues/2978#issuecomment-703987557)? Would be nice to have a way to know what's wrong without having to describe each resource and dig into those details.

**Comment by youngnick** [comment]
There's some shortcuts we can do (you can pick out the Reason or the Message of a single Condition, which would let us pick out the Reason and Message for the Valid Condition), but there doesn't seem to be a good way to concatenate lots of things in the custom column definition, so I think removing it for now is probably better.

**Comment by stevesloka** [comment]
> but there doesn't seem to be a good way to concatenate lots of things in the custom column definition

Could we just do that work when updating the status? We're setting the value of that field as a static string, why not just update when processing?

**Comment by youngnick** [comment]
Yes, we absolutely could do that. That's what I started in the initial Condition design, but I don't think it made it in in the end. In that case, I guess we would keep the column, as a rollup of all the Conditions.

**Comment by kushthedude** [comment]
So should this PR be closed ? 
/cc @youngnick

**Comment by youngnick** [comment]
Sorry @kushthedude, I think it's probably better, yeah. Let's see if we can fix up the field rather than removing it.

**Pull request closed without merging**
