### PR TITLE
Switch to Role for leaderelection resource RBAC

### PR DESCRIPTION
**Pull request by sunjayBhatia**
- New RoleBinding for new contour Role, named contour-rolebinding since we can't modify the existing one
- RBAC for leaderelection moved from contour ClusterRole to projectcontour/contour Role
- make appropriate changes to e2e tests

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
impetus was from https://github.com/projectcontour/contour/pull/4202#discussion_r760395054

switching to a namespace scoped role makes sense, though does require some changes to our example deployment and good release notes/expectation setting and downstream consumers knowing about the change

the namespace for the role is hardcoded in our code, could be swapped out by someone manually creating their own manifests or with further tooling (ytt overlays, etc?)

**Comment by sunjayBhatia** [comment]
would argue if we do it, this should maybe be a "major" change

**Comment by sunjayBhatia** [comment]
Need to work out the upgrade tests, current failure is:

```
RoleBinding.rbac.authorization.k8s.io "contour" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"contour"}: cannot change roleRef
```

**Comment by sunjayBhatia** [comment]
Will probably have to fiddle with the naming of resources since it seems modifying a rolebinding is a no-go, unless it is ok to delete and re-create as part of an upgrade

**Review by stevesloka — APPROVED** [review]
I think this is a great tiny security thing that helps out! One dependency I can think of is the helm chart needing an update possibly to handle the namespace.

**Comment by youngnick** [comment]
This is looking great! I think the changelog/release note is really important to get right on this one, I'll approve once that's done.

**Comment by sunjayBhatia** [comment]
might need a check to see if there are any merge issues, but should be good to review

**Review by skriss — COMMENTED** [review]
Change LGTM. We'll need to follow up with updates to several downstream consumers:
- operator
- Helm chart
- TCE
- anything else?

**Review by skriss — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by sunjayBhatia** [comment]
I'll open some issues on the relevant consumers so they are updated, once the next release is cut with this change

**Comment by sunjayBhatia** [comment]
https://github.com/projectcontour/contour-operator/pull/488 operator change, waiting on this one

**Pull request merged**
