### PR TITLE
bump controller-runtime and k8s deps

### PR DESCRIPTION
**Pull request by tsaarni**
This pull request contains following changes:

* Consolidates the previously separate PRs to bump k8s dependencies together with controller runtime.
  * #6623
  * #6696
  * #6624
* Removes `+required` from `ExtensionServiceReference.Name`
  * See https://github.com/projectcontour/contour/pull/6634#issuecomment-2308178563 for reasoning.

**Background:**

`sigs.k8s.io/controller-runtime` v0.19.0 includes a [breaking change](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.19.0) that necessitates updating it alongside `k8s.io/*` v1.31. 

`sigs.k8s.io/controller-tools` v0.16.x needs to be updated for `k8s.io/*` v1.31 [compatibility](https://github.com/kubernetes-sigs/controller-tools?tab=readme-ov-file#compatibility), which also prompted the re-generation of CRDs.

`sigs.k8s.io/controller-tools` v0.16.x started to processes `+required` annotations which were not processed before. We have `+required` field `HTTPProxy.spec.virtualhost.authorization.extensionRef.name` within the `+optional` embedded struct `HTTPProxy.spec.virtualhost.authorization.extensionRef`. Since the struct is embedded, it is always included, even if it hasn't been explicitly initialized.  maintain backward compatibility, the `+required` annotation was removed.

### CODE REVIEW

**Comment by tsaarni** [comment]
I believe the RBAC rules were changed by `make generate` because new deduplication in controller-tools [v0.16.0](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.0) [kubernetes-sigs/controller-tools#937](https://www.github.com/kubernetes-sigs/controller-tools/pull/937).

**Comment by tsaarni** [comment]
There is still an additional hurdle with the version bump. Following change in controller-tools [v0.16.0](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.0) 

> ✨ add support for kubernetes +required annotations https://github.com/kubernetes-sigs/controller-tools/pull/944

rightfully triggers new "required" entries to be generated to CRDs where `+required` was used in the type definition. 

In our API we have a `+required` field in `ExtensionServiceReference`
https://github.com/projectcontour/contour/blob/20e57df13892996163d185be60929296b0843ffb/apis/projectcontour/v1/httpproxy.go#L238-L240

which is used in `AuthorizationServer` as `+optional` field but it is embedded struct instead of **a pointer**  
https://github.com/projectcontour/contour/blob/20e57df13892996163d185be60929296b0843ffb/apis/projectcontour/v1/httpproxy.go#L249-L250

So consider `AuthorizationServer` is used in Go code 
https://github.com/projectcontour/contour/blob/20e57df13892996163d185be60929296b0843ffb/test/e2e/httpproxy/global_external_auth_test.go#L234-L238

even though it never sets `HTTPProxy.Spec.VirtualHost.Authorization.ExtensionServiceRef` it will be included in the request. Omitempty does not help here since we should have used a pointer for that to work. Now because `ExtensionServiceReference.Name` is set with `nil` value the newly implemented `+required` validation now kicks in and applying the configuration fails.

**Comment by tsaarni** [comment]
There are several other types that also use `+required`, but only `ExtensionServiceReference.Name` is causing the test suite to fail.

I believe backwards compatible fix would be to remove the `+required` from `ExtensionServiceReference.Name`. Although it seems illogical to reference to a non-existing resource, this approach shouldn't be any worse than previous state, since `+required` has never actually been enforced by the CRD.

Another option would be to change `HTTPProxy.Spec.VirtualHost.Authorization.ExtensionServiceRef` to a pointer, but that could potentially break external Go code relying on the API.

Any thoughts?

**Comment by sunjayBhatia** [comment]
> There are several other types that also use `+required`, but only `ExtensionServiceReference.Name` is causing the test suite to fail.
> 
> I believe backwards compatible fix would be to remove the `+required` from `ExtensionServiceReference.Name`. Although it seems illogical to reference to a non-existing resource, this approach shouldn't be any worse than previous state, since `+required` has never actually been enforced by the CRD.
> 
> Another option would be to change `HTTPProxy.Spec.VirtualHost.Authorization.ExtensionServiceRef` to a pointer, but that could potentially break external Go code relying on the API.
> 
> Any thoughts?

Looks like we missed out making the change to a pointer in https://github.com/projectcontour/contour/pull/4994

Since it is a v1 type seems like we should go the conservative approach here and do the former

**Review by sunjayBhatia — APPROVED** [review]
LGTM

**Pull request merged**
