### PR TITLE
test/e2e/gateway: Remove request mirror test

### LINKED ISSUE #4650: E2E test flake: Gateway API request mirror test
We've seen the Gateway API request mirror test flaking recently. Here's one example:

https://github.com/projectcontour/contour/runs/7566077014?check_suite_focus=true#step:7:222

Ideally we can find and address the flake, but if not, we should add retries into the test definition to avoid having to re-run manually.

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Covered by Gateway API v0.7.1 conformance

Closes #4650

### CODE REVIEW

**Comment by skriss** [comment]
Gateway API webhook is flaking/maybe not ready when we start executing the test, have seen similar things a couple times.

**Comment by skriss** [comment]
Also upstream mirror test failed on the first run here: https://github.com/projectcontour/contour/actions/runs/5213468387/jobs/9408648716

**Comment by sunjayBhatia** [comment]
> Also upstream mirror test failed on the first run here: https://github.com/projectcontour/contour/actions/runs/5213468387/jobs/9408648716

of course 🙃 this one has no failures https://github.com/projectcontour/contour/pull/5446

**Comment by sunjayBhatia** [comment]
> Gateway API webhook is flaking/maybe not ready when we start executing the test, have seen similar things a couple times.

submitted https://github.com/projectcontour/contour/pull/5457 to see if that helps

**Pull request merged**
