### PR TITLE
internal/envoy: Disable ECDHE-RSA-AES128-SHA and ECDHE-RSA-AES256-SHA ciphers

### LINKED ISSUE #2401: New Weak Ciphers Flagged in Qualys SSL Labs Scan
**What steps did you take and what happened:**

This appears to be a repeat issue of a past issue:
- Issue: https://github.com/projectcontour/contour/issues/823
- PR: https://github.com/projectcontour/contour/pull/1011

In that PR thread, it is written:

image

However when I scanned my site using https://www.ssllabs.com/ssltest/index.html new weak ciphers appear:

image

This is the YAML I used to produce the result: (A+ score when using cert-manager + letsencrypt)

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-proxy
spec:
  virtualhost:
    fqdn: website.com
    tls:
      secretName: my-tls
      minimumProtocolVersion: '1.2'
  routes:
    - conditions:
      - prefix: /
      services:
        - name: my-service
          port: 80
      enableWebsockets: true
```

**What did you expect to happen:**

No weak ciphers displayed in the scan result  page.

**Anything else you would like to add:**

While the grade is capped at A+, Contour might require updated configuration to improve Cipher Strength score:

image

**Some more information about the weak ciphers:**
- https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA/
- https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/

>  **Cipher Block Chaining:**

> The CBC mode is vulnerable to plain-text attacks with TLS 1.0, SSL 3.0 and lower. However a real fix is implemented with TLS 1.2 in which the GCM mode was introduced and which is not vulnerable to the BEAST attack. GCM should be preferred over CBC (cf. BEAST).

>  **Secure Hash Algorithm 1 MAC:**

> The Secure Hash Algorithm 1 has been proven to be vulnerable to collision attacks as of 2017 (cf. shattered.io). While this does not affect its usage as a MAC, safer alternatives such as SHA-256, or SHA-3 should be considered.

**Internet Explorer 11 is compatible with TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 and TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 cipher suites which are flagged as secure:**

https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%2010&key=107

**Environment:**

- Contour version: v1.3.0
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: kubeadm 

```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: UpCloud 2 Core 4 GB RAM

- OS (e.g. from `/etc/os-release`):

```env
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

/cc @yob

### PR DESCRIPTION
**Pull request by bascht**
This change is basically the 2020 version of 18d23790 and will solve #2401, since those CBC ciphers get flagged by recent versions of Qualys SSL Labs or [TestSSL](https://testssl.sh/).

Refs also #2880 and #2777 but is way less complex.

Closes #2401.

### CODE REVIEW

**Comment by youngnick** [comment]
Thanks for this PR @bascht! Looks like there are some failing tests though, could you run a local `make check` and fix them please? Alternatively, you can see the failures in the builds on the PR.

**Comment by bascht** [comment]
@youngnick oh yes absolutely. Thanks for the hint. `make check` looks alright now. :)

**Comment by youngnick** [comment]
Sorry, I forgot to check before, but we also need a DCO signoff in the commit, you can read more in our CONTRIBUTING.md.

**Review by youngnick — APPROVED** [review]
LGTM, I'll merge once the DCO is all good.

**Review by skriss — APPROVED** [review]
LGTM pending adding DCO signoff (`git commit --amend --signoff && git push -f` should do it).

**Comment by bascht** [comment]
Finally got around to add a sign-off, sorry for the wait!

**Comment by skriss** [comment]
@bascht any chance you can rebase this on top of latest `main` code too? 🙏

**Comment by bascht** [comment]
Sure! This is moving quickly! :grimacing:

**Comment by skriss** [comment]
@bascht yep, sorry for the churn :/ will get this merged as soon as CI is green again!

**Pull request merged**
