### PR TITLE
update docs & examples to match gateway-api/v1

### LINKED ISSUE #5919: Gateway API: update docs and examples for v1 API version
GatewayClass, Gateway and HTTPRoute will move to `v1` as of Gateway API 1.0. This issue is to update relevant documentation and examples to use that API version, where applicable.

- e.g. https://projectcontour.io/docs/main/config/gateway-api/
- e.g. https://projectcontour.io/docs/main/guides/gateway-api/

### PR DESCRIPTION
**Pull request by izturn**
Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)

fix #5919

### CODE REVIEW

**Comment by skriss** [comment]
Ready for a rebase now that the module bump has merged.

**Comment by izturn** [comment]
@skriss  PTAL

**Review by skriss — APPROVED** [review]
LGTM, thanks @izturn 

We should hold off on merging this until the time of the 1.28 release, since it updates some non-versioned docs that should still correspond to the latest released version, which doesn't yet support v1.

**Review by sunjayBhatia — APPROVED** [review]
LGTM, approving to get out of my review request queue 👀

**Comment by skriss** [comment]
Ready to merge just prior to cutting v1.28.0.

**Pull request merged**
