### PR TITLE
Dependency updates for release-1.22

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Bump go, golang.org/x/net+text, github.com/emicklei/go-restful manually

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
flake downloading kustomize, will re-run

**Comment by skriss** [comment]
Does it make sense to bump ginkgo/gomega here like you did for release-1.23?

**Comment by sunjayBhatia** [comment]
> Does it make sense to bump ginkgo/gomega here like you did for release-1.23?

yeah we could def do that, though the thought was to be a little more conservative on the older releases since the version changes in those tools was broader/to avoid debugging something unrelated

**Comment by skriss** [comment]
> > Does it make sense to bump ginkgo/gomega here like you did for release-1.23?
> 
> yeah we could def do that, though the thought was to be a little more conservative on the older releases since the version changes in those tools was broader/to avoid debugging something unrelated

Fair enough. I see there's no explicit version override for `golang.org/x/net` so that must be getting bumped as a result of one of the other ones?

**Comment by sunjayBhatia** [comment]
> > > Does it make sense to bump ginkgo/gomega here like you did for release-1.23?
> > 
> > 
> > yeah we could def do that, though the thought was to be a little more conservative on the older releases since the version changes in those tools was broader/to avoid debugging something unrelated
> 
> Fair enough. I see there's no explicit version override for `golang.org/x/net` so that must be getting bumped as a result of one of the other ones?

yeah the x/net bump makes the x/text bump a no-op

**Review by skriss — APPROVED** [review]
LGTM, upgrade test failures looked like probably flakes to me

**Pull request merged**
