### PR TITLE
crd/ContourDeployment: Add field 'Ports'

### PR DESCRIPTION
**Pull request by izturn**
add the field `Ports` to `crd/ContourDeployment` to enable set containerPort & nodePort for envoy service 

Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)

### CODE REVIEW

**Comment by skriss** [comment]
Could you explain what you're trying to accomplish with this change? Need to consider how this relates to Gateway Listeners' concept of Ports, which define the port a client would use to connect to the Gateway.

**Comment by izturn** [comment]
the main reason is to let user can set the `nodePort` number for  ServiceType: NodePort

**Comment by skriss** [comment]
xref https://github.com/projectcontour/contour/issues/4499

**Comment by skriss** [comment]
@izturn ack, will try to revisit this in the coming weeks. If you could add some more detail on your use case, that'd be helpful.

**Comment by izturn** [comment]
ping

**Comment by izturn** [comment]
@skriss @sunjayBhatia ping

**Comment by izturn** [comment]
ping @skriss @sunjayBhatia

**Comment by skriss** [comment]
I'm not crazy about specifying some port info in `ContourDeployment`, because I think it belongs with the Listener logically. Right now, a user can change the Listener definitions on the Gateway, and Contour will update the Service definition accordingly. However, ContourDeployment changes typically do _not_ result in changes to the underlying infra, due to the second paragraph [here](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayClass). That's just one illustration of why having port info stored in two different places can be problematic.

What if alternately, we did the following:
- we change the [behavior described here](https://github.com/projectcontour/contour/issues/4499#issue-1216076991) today, to set the NodePort value to the Listener's PortNumber value when a NodePortService is requested.
- if we did the above, then we could document that when requesting a NodePort service, it's not possible to get auto-assigned ports due to limitations in the Gateway API spec itself. If this is problematic for folks, then we have some justification to change the API spec upstream.

cc @sunjayBhatia interested in your thoughts here.

**Comment by skriss** [comment]
@izturn I am going to close this PR out and will keep an eye out for a new PR per https://github.com/projectcontour/contour/pull/4705#issuecomment-1371921283, thanks for the patience on this one!

**Pull request closed without merging**
