### PR TITLE
Updates Accessibility Assessment Issue #3835

### PR DESCRIPTION
**Pull request by johnnycase**
This pull request adds alt attributes to images and title attributes to iframes in the Contour site. The pull request updates #3835

### CODE REVIEW

**Comment by johnnycase** [comment]
Looks like the DCO is missing from some of my commits. I think it's from the commits where I merged upstream, do I need to rebase instead? Thanks!

**Comment by youngnick** [comment]
Yes, I think that rebasing from upstream is better, those merge commits are not the DCO bot's friend, sadly.

**Comment by johnnycase** [comment]
Ah, thank you! Can I run this past you before I try it? I would run this on my local copy. The origin is my fork of the contour repo. Sorry for all the questions, I am new to git. 

git fetch upstream
git rebase upstream/main
git push origin main

**Comment by youngnick** [comment]
Yes, you've got it.

After you've done this rebase, if you still have the merge commits, it's probably okay, we can work around it when we merge the PR, as we'll squash the commits down to one (which will have a DCO).

**Review by youngnick — APPROVED** [review]
This looks great, thanks!

**Review by skriss — APPROVED** [review]
LGTM, thanks @johnnycase!

**Pull request merged**
