### PR TITLE
use nonroot user vs nobody

### PR DESCRIPTION
**Pull request by dprotaso**
nobody does not have a valid home directory

Fixes: https://github.com/projectcontour/contour/issues/2984

### CODE REVIEW

**Comment by mattmoor** [comment]
This is a function of us rebuilding contour with distroless.

Contour runs on scratch (which doesn't even have `/etc/passwd`), so I'm not sure this is really an upstream problem.

ofc I wouldn't object to an upstream fix, but I don't think there's anything technically wrong with what contour is currently doing.

**Comment by dprotaso** [comment]
interesting I'm surprised `65534` in the examples work with scratch

**Comment by jpeach** [comment]
> interesting I'm surprised `65534` in the examples works with scratch - when on k8s - i guess there's no validation

AFAICT, accessing the home directory is a distress thing?

**Comment by dprotaso** [comment]
> AFAICT, accessing the home directory is a distroless thing?

No - distroless doesn't do anything special that requires a home directory.

The nobody user doesn't have a home directory by design - this seems to be [a linux convention](https://unix.stackexchange.com/questions/186568/what-is-nobody-user-and-group).

I'll close this out if you aren't using distroless as your base

**Pull request closed without merging**
