### PR TITLE
site: Fix links in tls-termination docs for change to Hugo

### PR DESCRIPTION
**Pull request by stevesloka**
Updates #3712

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Review by sunjayBhatia — COMMENTED** [review]
link change looks good, but maybe we should link this to the config file reference rather than an example?

**Comment by stevesloka** [comment]
@sunjayBhatia I updated the link to point to the configuration docs page for the fallback certificate.

**Review by sunjayBhatia — APPROVED** [review]

**Review by skriss — CHANGES_REQUESTED** [review]
should make the same update for the `main` version of the page so it sticks going fwd

**Comment by stevesloka** [comment]
+1 @skriss

**Review by skriss — APPROVED** [review]
:+1: LGTM!

**Pull request merged**
