### PR TITLE
internal/dag: set HTTPProxy with no routes/includes/tcpproxy invalid

### LINKED ISSUE #2835: an HTTPProxy with no routes, includes, or tcpproxy is marked as valid
**What steps did you take and what happened:**
Create the following `HTTPProxy`:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: empty
spec:
  virtualhost:
    fqdn: foo.bar.com
```

See that the proxy is marked as valid:
```bash
NAME    FQDN          TLS SECRET   STATUS   STATUS DESCRIPTION
empty   foo.bar.com                valid    valid HTTPProxy
```

**What did you expect to happen:**
The `HTTPProxy` should be marked invalid since it's "empty" and likely is a result of user error.

**Anything else you would like to add:**
We should also add either a kubebuilder validation or a Gatekeeper validation for this to give the user immediate feedback.

**Environment:**

- Contour version: `v1.7.0`

### PR DESCRIPTION
**Pull request by skriss**
Fixes #2835 

Signed-off-by: Steve Kriss <krisss@vmware.com>

This was what I had in mind for #2835. It does not attempt to solve the whole issue around inclusion described in #2141. It simply ensures that one of `spec.routes`, `spec.includes`, or `spec.tcpproxy` is defined/non-empty for each proxy.

I think this has value separate from addressing #2141, since it is a useful validation for folks who aren't using inclusion, and it shouldn't have any impact on inclusion chains, but let me know if I'm missing something.

Will likely rebase this on #2847.

### CODE REVIEW

**Review by jpeach — COMMENTED** [review]
This looks pretty reasonable to me. Note that the gatekeeper check isn't equivalent to the Contour check (which only tests root proxies).

**Review by youngnick — APPROVED** [review]
Yes, this LGTM.

**Comment by skriss** [comment]
> Note that the gatekeeper check isn't equivalent to the Contour check (which only tests root proxies).

Good point, I overlooked that. Thinking about whether I should change the Gatekeeper config, or the Contour code...

**Comment by skriss** [comment]
rebased & modified Gatekeeper validation to only apply to root proxies.

**Review by jpeach — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
LGTM

**Pull request merged**
