### PR TITLE
Bump gateway-api version to release-0.5 branch

### PR DESCRIPTION
**Pull request by sunjayBhatia**
For conformance fixes, until 0.5.1 is released

### CODE REVIEW

**Review by skriss — DISMISSED** [review]
:shipit:

**Comment by sunjayBhatia** [comment]
hm, doesnt quite work with codegen job since that grabs the version as well but the branch reference is dodgy

**Review by skriss — APPROVED** [review]
LGTM, I guess it won't pass CI until https://github.com/projectcontour/contour/pull/4664 is also merged?

**Comment by sunjayBhatia** [comment]
> LGTM, I guess it won't pass CI until #4664 is also merged?

yep, merged together they all pass!

**Pull request merged**
