### PR TITLE
fix links in documentation

### PR DESCRIPTION
**Pull request by pyaillet**
Thanks for making contour !

While following the [contour quickstart guide](https://projectcontour.io/getting-started/#option-1-quickstart), I stumbled upon some templating not rendered by hugo: `{{ .site.url }}`.

I didn't find any issue tracking this, event though #3712 seems related.
I'm not sure how to fix this, but I saw that the link was not coming from a template [in this page](https://projectcontour.io/guides/gateway-api/), so I used the same approach.

Feel free to tell me if you think this should be handled another way.

### CODE REVIEW

**Comment by skriss** [comment]
I *think* the Hugo way to do this would be to:

(1) in site/config.yaml, under `params`, add `base_url: "https://projectcontour.io"`
(2) update the content page to use e.g. `$ kubectl apply -f {{< param base_url >}}/quickstart/contour.yaml`

**Comment by sunjayBhatia** [comment]
probably good to get this done before the 1.16 release, gonna add it to the milestone (thanks @pyaillet!)

**Comment by skriss** [comment]
> I was just trying to test this with `{{ .Site.baseURL }}` but wasn't lucky to get it working.

Yeah from what I saw this syntax doesn't work in markdown files

**Comment by pyaillet** [comment]
> I was just trying to test this with `{{ .Site.baseURL }}` but wasn't lucky to get it working.

I tested many variations around this before and didn't manage to get it working, `< param base_url >` works fine though !

**Review by skriss — APPROVED** [review]
LGTM. If you merge the latest `main` into your branch, the CI failures should go away.

**Review by stevesloka — APPROVED** [review]
/lgtm Thanks @pyaillet!! 🎉

**Comment by jonasrosland** [comment]
Fantastic, thank you for this!

**Pull request merged**
