### PR TITLE
internal: Update contour package to xdscache and rename imports

### LINKED ISSUE #2938: internal: Update Contour import alias for Contour API
The Contour import alias for the contour api is currently `contourv1`. Since the refactoring the internal/contour package into `contourv2` and it's not clear which version we should use.  

We could use `contourv1api` or similar for the the Contour api. 

_Originally posted by @skriss in https://github.com/projectcontour/contour/pull/2928#discussion_r493837575_

### LINKED ISSUE #2939: internal: consider renaming `internal/contour/v2` to something more descriptive
The XDS caches have now been extracted to their own package, `internal/contour/v2`. Consider renaming this package to something more descriptive, for example `internal/xdscache/v2`.

### PR DESCRIPTION
**Pull request by stevesloka**
Renames the `contour` package to `xdscache` and fixes up all the imports
to make them consistent across the project.

Fixes #2938
Fixes #2939

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Review by skriss — APPROVED** [review]
This looks reasonable to me. It'd be helpful to document this standard, perhaps in https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md -- I'd like to see us document a few more of the conventions and standards that we use there, it's helpful for new contributors.

**Comment by skriss** [comment]
Also, this is probably going to conflict with a few open PRs...not sure what order we want to go in.

**Comment by youngnick** [comment]
Ah, oops, I forgot to check. The status change should be straightforward to fix. I won't merge anything more until this one is done - I think this should go next.

**Comment by skriss** [comment]
I merged the CORS PR, this is now ready for a rebase.

**Comment by jpeach** [comment]
Both of the linked issues seem reasonable to be, but can we make separate PRs for them? Is there a good reason that we need  to combine both large changes?

**Comment by stevesloka** [comment]
> Is there a good reason that we need to combine both large changes?

Nope no real reason other than making the review easier. The rename touches the same number of files as the package move, so the attempt was to make it easier on the reviewer to only validate the alias import changes.

**Comment by stevesloka** [comment]
The merge conflicts got to me trying to resolve, it will be easier to just do the work again from scratch. I'll split into two as well for @jpeach.

**Pull request closed without merging**
