### PR TITLE
Remove use of depcrated Envoy matchers. Fixes 4076

### PR DESCRIPTION
**Pull request by rajatvig**
internal/envoy: Remove use of deprecated functions

Moved all usages of `header_match` and `exact_match` with `string_match`

Fixes [#4076](https://github.com/projectcontour/contour/issues/4076)

Signed-off-by: Rajat Vig <rvig@etsy.com>

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
thanks for the change @rajatvig, one last thing, if you could write a short changelog following [this guide](https://github.com/projectcontour/contour/blob/7aecf1b4e5cdf1fa39129b5d6e4a9d5cf5969138/CONTRIBUTING.md#commit-message-and-pr-guidelines) that would be super helpful

**Comment by rajatvig** [comment]
> if you could put that release note in a file following this guideline, the build will automatically run on push:
> 
> (in this case changelog file name `4397-rajatvig-small.md`)
> 
> ```
> PRs must include a file named changelogs/unreleased/PR#-githubID-category.md, which is a Markdown file with a description of the change. Please see changelogs/unreleased/<category>-sample.md for sample changelogs.
> ```

My bad. Should have read the instructions more carefully. Updated with the changeling for both the issues.

**Comment by sunjayBhatia** [comment]
hey @rajatvig just gotta change the changelog filename to use this PR number

thanks for jumping through these hoops for us btw, really helps us generate good release notes!

**Review by sunjayBhatia — APPROVED** [review]

**Review by skriss — APPROVED** [review]
LGTM, thanks @rajatvig!

**Pull request merged**
