### PR TITLE
Apply correct image pull policy when running ingress conformance

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Running the conformance tests should work exactly the integration tests do: a locally built contour image is loaded in the kind cluster to test against. Without the change to image pull policy we end up always running tests against the `main` image pulled from docker hub.

### CODE REVIEW

**Comment by youngnick** [comment]
When we run the conformance test, how does the image pulling work? Do we generate a new image and push it into the kind cluster (tagged `main`)? If so, I think this change makes sense. Just want to check for posterity. :)

**Comment by sunjayBhatia** [comment]
> When we run the conformance test, how does the image pulling work? Do we generate a new image and push it into the kind cluster (tagged `main`)? If so, I think this change makes sense. Just want to check for posterity. :)

Yep, running the conformance tests should work exactly like that which is how the integration tests work. Without the change to image pull policy we end up pulling from docker hub.

**Review by stevesloka — APPROVED** [review]
Looks fine to me, just hard to test since these aren't enabled at the moment.

**Review by youngnick — APPROVED** [review]
This makes sense now, thanks @sunjayBhatia!

**Pull request merged**
