### PR TITLE
Add Flyte as adopter

### PR DESCRIPTION
**Pull request by OrlinVasilev**
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@skriss  indeed - waiting on @kumare3 feedback :)

**Comment by OrlinVasilev** [comment]
@kumare3 can you provide some info for the usage please as we discussed in slack , thanks!

**Comment by youngnick** [comment]
Awesome, thanks @kumare3! Looking forward to hearing more about the usage!

**Comment by kumare3** [comment]
So as a usage, Flyte's [sandbox environment](https://docs.flyte.org/en/latest/deployment/sandbox.html#deployment-sandbox) is powered by Contour and this is the default Ingress we ship with. Sandbox environment has made it possible for data scientists all over to try out Flyte quickly and without contour that would not have been easy.

**Comment by OrlinVasilev** [comment]
@skriss @kumare3 @youngnick added the text and fixed formatting!

**Review by sunjayBhatia — APPROVED** [review]

**Pull request merged**
