### PR TITLE
[release-1.22] update Envoy to v1.23.1 (#4691)

### LINKED ISSUE #4685: Contour v1.22.0 is broken on arm64 because of Envoy v1.23.0
**What steps did you take and what happened:**

I ran `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`, on a kind arm64 cluster.

The envoy container kept crashing:
```
❯ kgp -n projectcontour
NAME                                  READY   STATUS             RESTARTS         AGE
contour-58f874d79d-ssl8j              1/1     Running            0                3h50m
contour-58f874d79d-v92qj              1/1     Running            0                3h50m
contour-certgen-v1.22.0-9zs9w         0/1     Completed          0                3h50m
envoy-wbq8m                           1/2     CrashLoopBackOff   48 (3m33s ago)   3h50m
```

```
❯ k logs -f -n projectcontour envoy-xlp8z envoy
exec /usr/local/bin/envoy: exec format error
```

**What did you expect to happen:**
A working installation of contour (along with envoy) on my cluster

**Anything else you would like to add:**
This seems to be because of this: https://github.com/envoyproxy/envoy/issues/22261

**Environment:**

- Contour version: `v1.22.0`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-10T01:40:31Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
```
- Kubernetes installer & version: `kind v0.13.0 go1.18.2 darwin/arm64`
- Cloud provider or hardware configuration: N/A
- OS (e.g. from `/etc/os-release`): N/A

### PR DESCRIPTION
**Pull request by skriss**
Closes #4685.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Review by sunjayBhatia — APPROVED** [review]

**Comment by keithmattix** [comment]
Is there a patch release inbound for Envoy v1.23.1?

**Comment by skriss** [comment]
> Is there a patch release inbound for Envoy v1.23.1?

@keithmattix there will be - we were holding off for a bit to see if we could pick up the Gateway API v0.5.1 release as well, but seems like that may take a bit longer so we'll probably go ahead with the Contour patch release soon. I'll update here soon.

**Comment by keithmattix** [comment]
Awesome, thanks so much!

**Comment by skriss** [comment]
@keithmattix hot off the presses: https://github.com/projectcontour/contour/releases/tag/v1.22.1

**Pull request merged**
