### PR TITLE
upgrade tests: Correct "from" version for different git refs

### PR DESCRIPTION
**Pull request by sunjayBhatia**
- On a tag, use previous tag
- On a release branch, find previous tag on that branch
- On main or other refs, just use globally most recent tag

Also moves another script form hack into the test/scripts dir

Output from various branches:

branch main: `v1.16.0`

tag v1.16.0: `v1.15.1`

branch release-1.16 with an empty commit on top: `v1.16.0`

branch release-1.16 with no commit: `v1.15.1`

*Would be good to cherry-pick this back to the release-1.16 branch to keep CI there green*

Fixes: #3743

### CODE REVIEW

**Review by skriss — APPROVED** [review]
LGTM

**Review by stevesloka — APPROVED** [review]

**Comment by sunjayBhatia** [comment]
so just realizing, my only fear with this is the CI run on a PR to the release branch might fail 🤔

**Comment by sunjayBhatia** [comment]
see https://github.com/projectcontour/contour/pull/3747

**Comment by sunjayBhatia** [comment]
hmm, also within a release branch, this will only upgrade from the previous patch release, which might be ok but maybe we should test upgrading from the previous minor release?

**Comment by sunjayBhatia** [comment]
going to merge, our upgrade matrix will be something to continue to think about

**Pull request merged**
