### PR TITLE
Update architecture.md

### PR DESCRIPTION
**Pull request by michmike**
updating to include the second architecture diagram by Steve Sloka

### CODE REVIEW

**Comment by michmike** [comment]
@youngnick can you PTAL?

**Comment by jpeach** [comment]
Do you need to add `architecture_in_k8s.png`?

**Comment by youngnick** [comment]
Yeah, the second diagram is not present.

**Comment by youngnick** [comment]
ah, the file is in master, you'll need to rebase. Could you please include the image in this PR next time?

**Comment by michmike** [comment]
PR is not ready for review. i need to figure out how to resize this in a way netlify likes

**Comment by davecheney** [comment]
Please sign your commit. Thank you

**Pull request closed without merging**
