### PR TITLE
Add integration test to verify Host header rewrite policy

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Regression test to ensure host header rewrite policy is correct and
rewrites with literal value, regression introduced in xDS v2 -> v3
switch.

Merge after https://github.com/projectcontour/contour/pull/3252

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Added integration test should fail before https://github.com/projectcontour/contour/pull/3252 is merged into the branch

**Comment by sunjayBhatia** [comment]
See check run that fails as intended: https://github.com/projectcontour/contour/pull/3254/checks?check_run_id=1696330990

**Review by stevesloka — APPROVED** [review]
/lgtm but feels weird to merge with it breaking into `main`, so maybe can merge #3252 first, then watch this one go green?

**Comment by sunjayBhatia** [comment]
> /lgtm but feels weird to merge with it breaking into `main`, so maybe can merge #3252 first, then watch this one go green?

Yep, I would merge this after the one that fixes the regression so `main` stays green

**Review by skriss — APPROVED** [review]
LGTM!

**Comment by skriss** [comment]
@sunjayBhatia do you mind bumping the integration test number to 017 to avoid conflicting with https://github.com/projectcontour/contour/pull/3236? (I don't think it actually causes any problems to have dupes, but may as well avoid it since we have the numbers).

**Comment by skriss** [comment]
well I thought #3236 would merge before this, but we're waiting on docs for that one. I'll merge this one now but our integration test numbering will be missing 016 for a bit.

**Pull request merged**
