### PR TITLE
Revert "internal/envoy: disabled rest of the CBC mode ciphers (#3237)"

### PR DESCRIPTION
**Pull request by youngnick**
This reverts commit 88805b8af935900b734e8857a20fe0f320fb8946.

Sorry about this, @tsaarni, we'll replay this once we get a solution for #2880, since we have evidence other cipher deprecations have impacted at least one user in a big way (that's #3299).

Updates #3299

### CODE REVIEW

**Comment by youngnick** [comment]
Getting this one sorted out so we can merge asap if we all agree, so we can not hold up 1.12.0 any longer.

**Comment by tsaarni** [comment]
No problem!  Though it would be great to do #2880 soon since my organization needs to be compliant with [RFC7540 TLS 1.2 Cipher Suite Black List](https://tools.ietf.org/html/rfc7540#page-83) which lists these ciphers as having inadequate security.

I also wonder a bit about the asymmetry.  There is an equal set of ciphers flagged insecure for people that have RSA vs Elliptic Curve Cryptography based server certificates. These ciphers should go together. But I assume the idea is that the accident already happened for RSA versions and that is not wanted to be reverted? 

| cipher with RSA server certificate | cipher with EC server certificate |
| - | - |
| ~ECDHE-RSA-AES128-SHA~ | ~ECDHE-ECDSA-AES128-SHA~ |
| ECDHE-RSA-AES256-SHA | ECDHE-ECDSA-AES256-SHA |

**Comment by sunjayBhatia** [comment]
@skriss @stevesloka per @tsaarni’s comments should we revert the ciphers for RSA certificates as well in this PR (I think we have edit access so we could push a commit) or just make a second

**Comment by skriss** [comment]
> @skriss @stevesloka per @tsaarni’s comments should we revert the ciphers for RSA certificates as well in this PR (I think we have edit access so we could push a commit) or just make a second

I think we may as well revert the RSA ciphers too; indifferent between this PR or a second.

**Comment by sunjayBhatia** [comment]
> > @skriss @stevesloka per @tsaarni’s comments should we revert the ciphers for RSA certificates as well in this PR (I think we have edit access so we could push a commit) or just make a second
> 
> I think we may as well revert the RSA ciphers too; indifferent between this PR or a second.

https://github.com/projectcontour/contour/pull/3301

**Review by sunjayBhatia — APPROVED** [review]

**Review by skriss — APPROVED** [review]

**Comment by sunjayBhatia** [comment]
https://github.com/projectcontour/contour/pull/3304 will re-apply what was reverted here

**Pull request merged**
