### PR TITLE
[release-1.16 cherry-pick] upgrade tests: Correct "from" version for different git refs

### PR DESCRIPTION
**Pull request by sunjayBhatia**
- On a tag, use previous tag
- On a release branch, find previous tag on that branch
- On main or other refs, just use globally most recent tag

Also moves another script form hack into the test/scripts dir

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
yeah PR itself fails as it is a random branch: https://github.com/projectcontour/contour/pull/3747/checks?check_run_id=2696993324#step:6:190

**Comment by sunjayBhatia** [comment]
fears from these comments realized:
- https://github.com/projectcontour/contour/pull/3744#issuecomment-850600804
- https://github.com/projectcontour/contour/pull/3744#issuecomment-850607167

**Review by youngnick — APPROVED** [review]
LGTM, nice work.

**Comment by sunjayBhatia** [comment]
> does this mean future PRs to release branches will fail as well? Or just this one that's adding the new logic?

hmm yeah we're gonna have to delete the original certgen job as well, need another PR and to backport that

considering just setting the version to upgrade "from" in the workflow as well, since b/c of the way github checks out the commits, it isn't on a branch so we just know to check out the globally latest tag

**Comment by sunjayBhatia** [comment]
> does this mean future PRs to release branches will fail as well? Or just this one that's adding the new logic?

added https://github.com/projectcontour/contour/pull/3762 and https://github.com/projectcontour/contour/pull/3761 to help with this as well

**Review by skriss — APPROVED** [review]

**Pull request merged**
