### PR TITLE
Pare down docs version in site dropdown

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Include main plus last 5 minor releases in site dropdown (include patch releases)

Docs pages are retained to ensure links to old docs are still valid

### CODE REVIEW

**Review by youngnick — APPROVED** [review]

**Review by stevesloka — COMMENTED** [review]
This is probably ok to remove, the only good part about leaving it is that any links to older versions will still work. 

//cc @jonasrosland

**Comment by jonasrosland** [comment]
As a preservationist it hurts me to delete docs like this :)
The dropdown menu should definitely be pared down to only show more recent versions, but I'm not sure what the harm is in keeping the files in place?

**Comment by sunjayBhatia** [comment]
> As a preservationist it hurts me to delete docs like this :)
> The dropdown menu should definitely be pared down to only show more recent versions, but I'm not sure what the harm is in keeping the files in place?

Fine with closing this if this is overkill, just felt like this old content was probably not being used and adding to clutter in the repo

**Comment by youngnick** [comment]
I approved because I kind of don't think that the really old docs are very relevant any more, but I don't see any issue with leaving them there if people feel strongly.

**Pull request merged**
