### PR TITLE
Update k8s deps for 1.21.0 release

### PR DESCRIPTION
**Pull request by sunjayBhatia**
No kind image yet so no update to tested k8s versions yet

### CODE REVIEW

**Comment by stevesloka** [comment]
Could you also update the support matrix bits as well?

**Comment by sunjayBhatia** [comment]
I'll add an Issue for the 1.15.0 release, since we're not actually testing against 1.21.0 yet (no kind image) I would hold off on changing the matrix

**Comment by sunjayBhatia** [comment]
https://github.com/projectcontour/contour/issues/3583

**Comment by youngnick** [comment]
I think we should add a 'main` line to the support matrix, that makes keeping everything up to date much easier. In addition, we probably need to remove really old versions.

**Comment by sunjayBhatia** [comment]
> I think we should add a 'main` line to the support matrix, that makes keeping everything up to date much easier. In addition, we probably need to remove really old versions.

https://github.com/projectcontour/contour/pull/3605

**Review by youngnick — APPROVED** [review]

**Pull request merged**
