### PR TITLE
docs: guides/cert-manager

### LINKED ISSUE #2800: [site][guides/cert-manager] Incorrect secret name value for `httpbinproxy` resources
**What steps did you take and what happened:**
I followed all the steps in [Deploying HTTPS services with Contour and cert-manager](https://projectcontour.io/guides/cert-manager/) as is. While the steps for getting certs for the `httpbin` sub-domain worked as expected, but the steps for the `httpbinproxy` sub-domain didn't get the cert.

**What did you expect to happen:**
Get a TLS cert for my sub-domain related to `httpbinproxy`

**Anything else you would like to add:**
In the steps for `httpbinproxy` with HTTPProxy resource, the secret name is still specified as `httpbin` and not `httpbinproxy`. When I changed the secret name in both `HTTPProxy` & `Ingress` resource manifests, it worked as expected.

Another thing I noticed - The namespace for the dummy Ingress object is set to `default`. It's the only resource in the guide for which the default namespace is specified. While debugging the cert issue, I also changed it. 

I wanted to confirm that this is the right reason, and I'm not doing something wrong. If so, I'd be happy to raise a PR for fixing it. Please let me know if any more information is needed. Thanks 🙂

**Domains where I made it work (still live, so can be checked):**

- https://httpbinproxy.rajat404.com/
- https://httpbin.rajat404.com/

**Environment:**

- Contour version: v1.7.0
- Kubernetes version: (use `kubectl version`): v1.18.6
- Kubernetes installer & version: (not sure what's meant by installer 😓)
- Cloud provider or hardware configuration: DigitalOcean 
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)
- Kernel Version: 4.19.0-0.bpo.6-amd64

### PR DESCRIPTION
**Pull request by rajat404**
Set correct `secretName` for resources related to `httpbinproxy`.
Also set correct namespace for the dummy ingress object.

Fixes #2800

Signed-off-by: Rajat Goyal <404rajat@gmail.com>

### CODE REVIEW

**Comment by rajat404** [comment]
One of the integration tests is failing.
Not able to figure out why (given that i didn't change anything in code) 🤔 

Can someone please help me out here 🙏

**Comment by rajat404** [comment]
Ah! It's passing now 🎉 
Can you please share if the build failure happened due to a flaky integration test, or something else? (just curious)

**Comment by youngnick** [comment]
I suspect it was a flaky test - it was the SNI check. I triggered a rerun and it seems to have passed now.

**Comment by rajat404** [comment]
Thanks a lot for the quick review & merge 🙏 
This was a really nice experience 😄

**Pull request merged**
