### PR TITLE
Re-disable insecure AES128/256 ciphers by default

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Re-applies #3237 and #3154
    
Blocked on #3300 and #3301 and should be merged for 1.13.0 release

### CODE REVIEW

**Review by youngnick — COMMENTED** [review]
This LGTM, but I'd like to see #3292 go in first, just so we can be sure we can fix this later.

**Comment by skriss** [comment]
LGTM. Are we going to do this for 1.13, or hold off for another release? (I think we talked about this but I can't recall the decision)

**Comment by sunjayBhatia** [comment]
> LGTM. Are we going to do this for 1.13, or hold off for another release? (I think we talked about this but I can't recall the decision)

There was this comment which I think implied we should do it in 1.13: https://github.com/projectcontour/contour/issues/3299#issuecomment-774785433

**Review by skriss — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
This LGTM, but we really need to figure out how we're going to document which ciphers are the default, and which are available in Envoy.

**Comment by sunjayBhatia** [comment]
> This LGTM, but we really need to figure out how we're going to document which ciphers are the default, and which are available in Envoy.

Right now this section https://projectcontour.io/docs/main/configuration/#tls-configuration has a link to https://pkg.go.dev/github.com/projectcontour/contour/pkg/config#pkg-constants which will get updated to show the ciphers we allow when we cut a release (should actually be fixed to https://pkg.go.dev/github.com/projectcontour/contour/pkg/config#pkg-variables). It also links to https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-field-extensions-transport-sockets-tls-v3-tlsparameters-cipher-suites.

We could document these in-line as well and/or add another configuration/guide page for "Advanced TLS Configuration" that describes our cipher default selection and how to override it.

**Comment by youngnick** [comment]
That sounds fine to me. I'll merge this one now.

**Pull request merged**
