### PR TITLE
Feature/migrate docs to hugo

### PR DESCRIPTION
**Pull request by prondubuisi**
This branch attempts to fix merge conflicts with the `main` branch in iterations.

The first commit updates `sites/data` and `netlify.toml`

To test this out
`cd site`

then run
`hugo server`

Hello @jonasrosland If this is in order I can go ahead and update other folders, thanks.

### CODE REVIEW

**Comment by prondubuisi** [comment]
Also @jonasrosland I wonder why some of these files show as merge conflicts when they have been deleted or moved to another folder

**Comment by jonasrosland** [comment]
These changes look good!

**Comment by jonasrosland** [comment]
> Also @jonasrosland I wonder why some of these files show as merge conflicts when they have been deleted or moved to another folder

I think it's because they were updated in the repo between the time that work started on the Hugo site, and now. Based on comments from @skriss they should be minor changes, such as whitespaces.

**Comment by sunjayBhatia** [comment]
@prondubuisi @jonasrosland is there anything we can help out with here to get it moving forward?

**Comment by prondubuisi** [comment]
Hello @sunjayBhatia , I think @jonasrosland  is making another Pull request from scratch, as it is difficult to keep track of the changes since the initial branch.

**Comment by sunjayBhatia** [comment]
given the comments above and some conversation in slack, we can close this as a fresh PR is going to be provided

**Pull request closed without merging**
