### PR TITLE
RFC: Add `--envoy-ingress-name`, and `--envoy-ingress-namespace` flags. (#4952)

### PR DESCRIPTION
**Pull request by kahirokunn**
https://github.com/projectcontour/contour/issues/4952

I want to add `--envoy-ingress-name` and `--envoy-ingress-namespace`.
I'm thinking something like this, what do you think?
If you like it, I can implement the rest.

### CODE REVIEW

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by skriss** [comment]
@kahirokunn first of all I want to apologize for how long it's taken us to review this. We appreciate your contributions to the project!

One thought I have here - maybe instead of having a pair of flags/config fields for Service, Ingress, Gateway, etc., we could just have three flags/fields -- resource type, namespace, and name. This would help avoid flag/config sprawl, and would be more extensible for any future ways of sourcing the LoadBalancerStatus. If we do like this pattern, then we need to decide whether we want to keep the existing fields for Service namespace/name, or deprecate them and replace them with more generally named fields. Deprecation is possible but requires a series of changes over multiple releases to allow folks a chance to migrate to the replacements. What are your thoughts on this approach?

**Comment by kahirokunn** [comment]
@skriss I agree, because that approach worked in all cases with minimal code.
If you want, I can implement it myself.

**Comment by skriss** [comment]
> @skriss I agree, because that approach worked in all cases with minimal code. If you want, I can implement it myself.

:+1: I'd like to get @sunjayBhatia and/or @tsaarni's input here as well before we move forward. Also, if you could take a look at #2539 and see if anything there would impact our approach here, that would be great! I haven't had a chance to review that issue in detail myself yet.

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
@skriss https://github.com/projectcontour/contour/issues/2539
This issue does not affect my problem, but if I implement your suggestion the issue will be resolved.

> we could just have three flags/fields -- resource type, namespace, and name

**Comment by kahirokunn** [comment]
@sunjayBhatia @tsaarni's Could you give me your opinion?

**Comment by kahirokunn** [comment]
keep

**Review by tsaarni — COMMENTED** [review]
I'm not too familiar with this area, but the idea looks OK to me. 

To me it seems aligned with what we already have for `Service`, and I cannot see it conflicting with having future status discovery/update methods like #2539, since I assume they always need to be mutually exclusive: only one method should be used at a time. Arming two watchers that fight to update status should be considered (and handled early) as a misconfiguration, right? That could be clearer in future documentation too.

BTW, I needed to read your comment here https://github.com/projectcontour/contour/issues/4952#issuecomment-1374330673 to understand the use of this functionality! :smile:

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by tsaarni** [comment]
Since there were no objections to suggestion https://github.com/projectcontour/contour/pull/5083#issuecomment-1498347249 it would be great to have short API proposal here - to get this PR unblocked! :sweat_smile: 

@skriss wrote: 
> One thought I have here - maybe instead of having a pair of flags/config fields for Service, Ingress, Gateway, etc., we could just have three flags/fields -- resource type, namespace, and name. This would help avoid flag/config sprawl, and would be more extensible for any future ways of sourcing the LoadBalancerStatus. 

One more thought: what do people think about single switch with format like `DISCOVERY_SCHEME:PARAMS`, for example `--loadbalancer-status=service:namespace/resource`, `--loadbalancer-status=ingress:namespace/resource`, `--loadbalancer-status=hostname:fqdn,hostname:fqdn` ...

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by skriss** [comment]
I like @tsaarni's suggestion above for the flag design.

@kahirokunn to move this forward, could you write up a brief summary of the changes we plan here, taking into account the comments above? In short, I think we would be adding two new generic flags that would provide the existing functionality for getting the IP from a Service, adding the functionality to alternate get it from an Ingress, and then deprecating the existing `--envoy-service-name/namespace` flags (but we can't remove them for a couple of releases).

Assuming everyone supports that approach, then we can move forward with the implementation.

**Comment by kahirokunn** [comment]
@skriss Sorry, I agree with you.
However, I have lost track of time and it looks like I will not be able to proceed with this implementation.
I would appreciate it if someone else could implement a new one instead.

**Pull request closed without merging**
