### PR TITLE
 grpc httpProxy example added

### PR DESCRIPTION
**Pull request by surajchhetry**
this is an example of how HttpProxy can be configured to access GRPC backed service #3432

### CODE REVIEW

**Review by sunjayBhatia — CHANGES_REQUESTED** [review]
Could you provide some more detail in the title and PR description about this change?

As I understand it, this is an example to show exactly how a GRPC service can be configured which was missing from our examples.

Also some comments in the example YAML about relevant portions would be great (why the `h2c` protocol is specifically chosen and when you might want to not use it, etc.)

**Comment by surajchhetry** [comment]
@sunjayBhatia updated with the requested change.

**Comment by stevesloka** [comment]
Looks good to me @surajchhetry! Could you look at the failures for the `codegen` job? Looks like a couple small spacing issues.

**Review by youngnick — APPROVED** [review]
I think this is a good start on further gRPC documentation, but eventually I'd like to see a better guide that covered more of the options (like using the service annotation vs the `protocol` field, `h2c` vs `h2` and so on).

Thanks @surajchhetry!

**Comment by skriss** [comment]
@surajchhetry are you able to address the feedback in https://github.com/projectcontour/contour/pull/3433#issuecomment-793030837 so we can merge this?

**Pull request closed without merging**
