### PR TITLE
upgrade k8s.io/client-go & related libs to v0.19.2

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
Does this fix any issues? Any effect on the Kubernetes versions that we support?

**Comment by skriss** [comment]
Nothing specific, just keeping us up to date. Per https://github.com/kubernetes/client-go#compatibility-client-go---kubernetes-clusters this brings us up-to-date with 1.19 clusters.

**Comment by jpeach** [comment]
xref  https://github.com/projectcontour/contour/issues/3003

**Review by stevesloka — APPROVED** [review]
/lgtm

**Pull request merged**
