### PR TITLE
internal/envoy: Enable xDS v3 Clusters

### PR DESCRIPTION
**Pull request by stevesloka**
Enables v3 xDS Clusters as well as supporting structs.

Updates #1898

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
Is it possible going forward to make a first commit that copies files from v2->v3 as-is, and then a second commit that does all the fixup to make it work for v3? I think it'll make it much easier to review since we can just look at diffs on the second commit.

**Comment by skriss** [comment]
I assume you're holding off on wiring this up to the v3 xDS servers for another PR?

**Comment by stevesloka** [comment]
> Is it possible going forward to make a first commit that copies files from v2->v3 as-is, and then a second commit that does all the fixup to make it work for v3? I think it'll make it much easier to review since we can just look at diffs on the second commit.

Yup I can do that now. The one bit is there are a few things partially moved due to needing them in v3 bootstrap.

**Comment by stevesloka** [comment]
> The one bit is there are a few things partially moved due to needing them in v3 bootstrap.

My thought was to

1. Get the conflicting bits merged into v3
2. copy/paste other files from v2 --> v3
3. Bump up the v3 copied files into v3 version
4. Upgrade feature tests

Probably need to to do this at some smallish rate to make it easier?

**Pull request closed without merging**
