### PR TITLE
Make lint/staticcheck happy

### PR DESCRIPTION
**Pull request by izturn**
Package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code.

Signed-off-by: Gang Liu <gang.liu@daocloud.io>

### CODE REVIEW

**Review by tsaarni — APPROVED** [review]

**Review by tsaarni — CHANGES_REQUESTED** [review]
Shouldn't we step minumum go version in `go.mod` to 1.16 since the replacement functions for the deprecated `ioutil` were also introduced in that version?

In the PR's CI checks [lint gets killed with error code 137](https://github.com/projectcontour/contour/runs/7760857339?check_suite_focus=true#step:3:87) but no other output for some reason, possibly https://github.com/golangci/golangci-lint/issues/576?

**Comment by lewgun** [comment]
i think we should upgrade to go1.18, because with the **go release policy**  the other versions below it will not be supported by go team, @tsaarni  what's your opinion ?

**Comment by tsaarni** [comment]
> i think we should upgrade to go1.18, because with the **go release policy** the other versions below it will not be supported by go team, @tsaarni what's your opinion ?

I dont have strict opinion but I do recall [this response](https://github.com/projectcontour/contour/issues/4349#issuecomment-1043029475) from @sunjayBhatia which makes sense to me. Though I have not tested if the code actually compiles with old compilers? :)

**Comment by lewgun** [comment]
got it, so let's upgrade it to go1.16?

**Comment by izturn** [comment]
done

**Review by tsaarni — APPROVED** [review]
LGTM :+1:

I still wonder why the lint step in CI check now constantly [fails with error 137](https://github.com/projectcontour/contour/runs/7763283989?check_suite_focus=true#step:3:87)? I don't think there is anything wrong in the PR and running golangci-lint-1.45.0 locally for it succeeded. I wonder if this is rather related to github's environment. BTW @sunjayBhatia is in the middle of updating the version of golanci-lint https://github.com/projectcontour/contour/pull/4661 but I don't know if that would fix this.

**Comment by tsaarni** [comment]
>   wonder if this is rather related to github's environment. BTW @sunjayBhatia is in the middle of updating the version of golanci-lint #4661 but I don't know if that would fix this.

The same happens with an "empty" PR :thinking: Since @sunjayBhatia 's PR #4661 seemed to be running ok with newer golangci-lint, maybe that needs to go in first.

**Comment by sunjayBhatia** [comment]
@izturn you should be able to rebase or merge `main` and focus this change on just switching from `ioutil` to the `os` package and bumping the go.mod go version to 1.16, other lint issues have been taken care of

**Comment by lewgun** [comment]
@sunjayBhatia  only ioutil => os, not ioutil => io ?

**Comment by lewgun** [comment]
done

**Comment by izturn** [comment]
@sunjayBhatia unfortunately, after merging with **main**, there are more issues about **github.com/goalng/protobuf**, so I exclude them, in **.golangcl.yml**, it's passed in my local dev env, but why it fall in the **action**?

**Comment by izturn** [comment]
done

**Review by sunjayBhatia — APPROVED** [review]

**Pull request merged**
