### PR TITLE
internal/dag: fix Gateway API HTTPS/TLS protocol handling

### LINKED ISSUE #4629: Gateway API Listeners with protocol TLS should only support TLS passthrough
ref. https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.ProtocolType
ref. https://gateway-api.sigs.k8s.io/guides/tls/#clientserver-and-tls

Listeners with a protocol of `TLS` accept TLS-encrypted TCP traffic (**not** assumed to be HTTP). Gateway API allows for TLS to either be passed through to the backend, or terminated at the proxy for this protocol. In the first case (TLS passthrough), `TLSRoute` must be used to route traffic to the backend, since it's still TLS-encrypted. In the second case (TLS termination), `TCPRoute` must be used to route traffic, since it may be non-HTTP traffic.

Contour does not and will not support `TCPRoute`, so as a result we should only be supporting TLS passthrough on Listeners using the TLS protocol.

Note that the HTTPS protocol covers the case of TLS-encrypted HTTP traffic with TLS terminating at the proxy.

### PR DESCRIPTION
**Pull request by skriss**
Requires the HTTPS listener protocol to
be used with TLS mode Terminate (compatible
with HTTPRoutes) and the TLS protocol to
be used with TLS mode Passthrough (compatible
with TLSRoutes).

Closes #4629.

Signed-off-by: Steve Kriss <krisss@vmware.com>

The actual change is pretty straightforward, but a bunch of our tests were inadvertently using invalid combos of protocols and modes that had to be cleaned up.

For reference, https://gateway-api.sigs.k8s.io/guides/tls/ provides the best explanation of how this is intended to work.

### CODE REVIEW

**Review by sunjayBhatia — APPROVED** [review]
looks good! also makes tests etc. a lot simpler which is nice

**Comment by skriss** [comment]
Gonna leave this open so @youngnick can take a look and make sure I'm not missing anything re: the spec.

**Review by youngnick — APPROVED** [review]
This LGTM, but I would ask if @skriss thinks that we could clean up the Gateway spec here? Is it clear enough that certain Protocols map to certain Routes?

**Comment by skriss** [comment]
> This LGTM, but I would ask if @skriss thinks that we could clean up the Gateway spec here? Is it clear enough that certain Protocols map to certain Routes?

https://gateway-api.sigs.k8s.io/guides/tls/ does a good job of laying it out, but I don't think it's super clear in the API documentation itself. It's an intersection of protocol, TLS mode, and route types, so would have to think about the best place to update. I will take a look.

**Pull request merged**
