### PR TITLE
Bump Go to 1.23.2

### PR DESCRIPTION
**Pull request by tsaarni**
This pull request includes following changes

* Updates Go major version from 1.22 to 1.23
  * See release notes: https://go.dev/doc/devel/release#go1.23.0 
* Updates golangci-lint to v1.61.0
  * [v1.60.1](https://github.com/golangci/golangci-lint/releases/tag/v1.60.1) added Go 1.23 support
* Lint fixes.

### CODE REVIEW

**Comment by tsaarni** [comment]
Marking as draft for now. There are gosec "G115: integer overflow conversion" errors, as well as some other lint errors that should be easier to fix.

**Comment by tsaarni** [comment]
I've fixed the simpler issues, but the remaining errors are gosec G115 integer overflow warnings. See details [here](https://gist.github.com/tsaarni/73e1a47451c326be6fa998bc24f8ac25).

In some respect, the errors seem valid and could be viewed as bugs. Some come from inconsistencies between CRD API types and Envoy API types. Changing the API types now could break backward compatibility. While it could be theoretically possible to add bounds checks and consider how to propagate errors to handle these edge cases, I’m unsure if it is practical.

I saw some cases where fixing the issue might not be even feasible, such as with `int` index variables in Go’s range loops:

```go
for index  := range values {
    // then process index in uint32 context
    // will cause error: G115: integer overflow conversion int -> uint32
}
```

One option is to keep the G115 on, but disable it for each remaining error with `//nolint:gosec // disable G115`.

What do you think?

**Comment by zjtv** [comment]
in our product, we use the same way:
```
I have some doubts there are meaningful ways to escalate thee errors so one option is to keep the G115 on, but disable it for each remaining error with //nolint:gosec // disable G115.
```

**Comment by izturn** [comment]
in our product, we use the same way:
```
I have some doubts there are meaningful ways to escalate thee errors so one option is to keep the G115 on, but disable it for each remaining error with //nolint:gosec // disable G115.
```

**Comment by tsaarni** [comment]
Thanks @izturn. I took this approach, except for couple of places, where I could fix the errors with small effort.

**Review by izturn — APPROVED** [review]
/lgtm

**Pull request merged**
