### PR TITLE
Updating contour description in website doc

### PR DESCRIPTION
**Pull request by bhks**
Updating contour description in website doc for HA mode and its functional behavior of what to expect as a user/operator.

### CODE REVIEW

**Comment by bhks** [comment]
Label:release-note/docs

**Review by skriss — APPROVED** [review]
LGTM, thanks @bhks!

**Comment by skriss** [comment]
@bhks just need you to add DCO signoff to your commits -- see https://github.com/projectcontour/contour/pull/4893/checks?check_run_id=9837298591 for details on how to resolve. Thanks

**Comment by skriss** [comment]
I put up #4943 to get this through, closing this one out.

**Comment by bhks** [comment]
My apologies I got to it but it was taking my amazon email Id and hence had to change some git global preferences and got lazy. Thanks for putting that out. 

My bad it got out of track.

**Pull request closed without merging**
