### PR TITLE
ci: Fix siteproof

### PR DESCRIPTION
**Pull request by sunjayBhatia**
- Add user agent to htmlproofer check as Twitter rejects non-browsers and out of date browsers
- Fix latest blog post

Fixes https://github.com/projectcontour/contour/issues/3229

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Could also replace the `Contour Team` author with one of the original authors of course

**Review by skriss — APPROVED** [review]
This WFM, alternately fine with adding Daneyon as an author too

**Review by stevesloka — APPROVED** [review]
/lgtm

**Comment by skriss** [comment]
https://github.com/projectcontour/contour/runs/1652308375#step:4:369 :(

**Comment by sunjayBhatia** [comment]
> https://github.com/projectcontour/contour/runs/1652308375#step:4:369 :(

thats a new one :(

**Pull request merged**
