### PR TITLE
test/e2e/httpproxy: Add test for gRPC server behind Contour with h2c

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Adds test verification for plaintext gRPC server

Part of sequence of PRs that will add test verification for various gRPC
configurations, and a guide to set up gRPC with Contour.

Uses test fixture from github.com/mhausenblas/yages which may be
replaced with a more fully featured option.

Updates: #1894

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
hm, thought the retries and timeouts would fix flakiness, gotta do a little more investigation, maybe add some backoffs to the retries

**Review by skriss — COMMENTED** [review]
This looks great to me -- I'm not too familiar with the gRPC-web stuff but looks like you've got it sorted out. Are they passing consistently or is there still some flakiness?

**Comment by sunjayBhatia** [comment]
> This looks great to me -- I'm not too familiar with the gRPC-web stuff but looks like you've got it sorted out. Are they passing consistently or is there still some flakiness?

i think with these retry options its looking pretty stable: https://github.com/projectcontour/contour/pull/4648/files#diff-ee633bab9384727cc410aa9165052e4aa38763741c18bdd1609c33a9b9159048R98-R104, the main flakiness i was seeing earlier was the service not being healthy so this mimics our requestuntil logic (maybe even more forgiving w/ exponential backoff)

**Review by skriss — APPROVED** [review]
LGTM, this is great to get codified!

**Comment by sunjayBhatia** [comment]
> LGTM, this is great to get codified!

if we do end up allowing the grpc-web filter to be disabled, should help there too

docs guide coming soon as well

**Pull request merged**
