### PR TITLE
Update the Community Page on the Website

### PR DESCRIPTION
**Pull request by Anuran12**
Close: #4787 

I updated the links of mailing list and changed some meeting information with the help of @pnbrown

### CODE REVIEW

**Comment by pnbrown** [comment]
@Anuran12 can you resolve the failing DCO check above?

**Comment by Anuran12** [comment]
> @Anuran12 can you resolve the failing DCO check above?

how can i resolve ? i don't know..... tell me please..

**Comment by pnbrown** [comment]
There are some instructions on the action. If you're having difficulty still, I can help walk you through it. The easiest way I've found to handle it is in GitHub Desktop by squashing commits, signing off in the new commit message, and pushing that branch.

**Comment by Anuran12** [comment]
@pnbrown I did it according to the instruction...

**Review by pnbrown — APPROVED** [review]

**Comment by pnbrown** [comment]
LGTM @Anuran12. We'll wait for one of the maintainers to review and see about getting this merged. Thank you. Feel free to check out some of our other open issues.

**Review by skriss — APPROVED** [review]
LGTM, thanks @Anuran12

**Pull request merged**
