### PR TITLE
design: Update rate limit design for HTTPProxy

### PR DESCRIPTION
**Pull request by stevesloka**
Updates #873 for HTTPProxy instead of IngressRoute. 

Also, moves the design from args to Contour to the configuration file. 

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by stevesloka** [comment]
@youngnick I think I've addressed all the comments around support and config defaults.

**Comment by iyacontrol** [comment]
when the rate limiting of contour is released?

**Comment by stevesloka** [comment]
Hey @iyacontrol & @bill-within, I'm going to update this design one more time then once we all agree should be able to code it up quickly (the work was done already). I'm going to see if we can get it ready for the Contour 1.5 release, but need to chat with the team on that priority.

**Comment by iyacontrol** [comment]
> Hey @iyacontrol & @bill-within, I'm going to update this design one more time then once we all agree should be able to code it up quickly (the work was done already). I'm going to see if we can get it ready for the Contour 1.5 release, but need to chat with the team on that priority.

woops! Thank you very much for your reply. We urgently need the rate limiting. Thanks again for your work.

**Comment by stevesloka** [comment]
The ideas around this have changed since merging the auth proposal, closing to rewrite against the new ideas.

**Pull request closed without merging**
