### PR TITLE
site: combine compatibility matrices into a single page

### LINKED ISSUE #3222: combine Envoy, Kubernetes, and (new) Operator compatibility matrices into a single page
Currently we have separate pages for Envoy and Kubernetes compatibility matrices. We'd also like to add one for the operator. We should consolidate these into a single page/matrix that indicates the various compatibilities for each Contour release.

### PR DESCRIPTION
**Pull request by skriss**
Combines the existing Envoy and Kubernetes compatibility matrix pages
into a single page, and adds Contour Operator compatibility to it.

Closes #3222.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Review by sunjayBhatia — APPROVED** [review]

**Review by stevesloka — APPROVED** [review]
/lgtm

**Comment by skriss** [comment]
I confirmed that the siteproof check failure is just noise due to (a) new links that aren't yet live and (b) spurious errors for some twitter links.

**Comment by skriss** [comment]
@youngnick feel free to merge if you're happy with this, otherwise I'll address any feedback in the new year.

**Review by youngnick — APPROVED** [review]
LGTM, thanks @skriss

**Pull request merged**
