### PR TITLE
internal/envoy: Disable CHACHA20 ciphers

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Related to an ask that Contour is FIPS compliant by default. Envoy built with
BoringSSL-FIPS removes the CHACHA20 ciphers by default.

Fixes https://github.com/projectcontour/contour/issues/2878

Note: Should probably merge after https://github.com/projectcontour/contour/pull/3292

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Open question, should we do this in 1.13 since we plan for https://github.com/projectcontour/contour/pull/3292 to be done then too? Or wait for 1.14 to give people some time to adapt?

**Comment by xaleeks** [comment]
I vote we announce this in the 1.13 and perform the deprecation on the following release, so folks have some time to react.  We should release this concurrent to or after the FIPS configurability capability is released so people can customize the specific list of ciphers they need.

**Comment by jpeach** [comment]
There's a good use case for an easy FIPS-mode, but I don't think that FIPS is an end in itself or necessarily a good default in general. AFAIK CHACHA20 cipher suites are valid, reasonable and secure choices. 

https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility

**Comment by youngnick** [comment]
Yes, I agree that FIPS should not be Contour's default. We should make it *possible* to do FIPS, and document what you have to do, but I don't think that FIPS should be the default.

I agree that we shouldn't turn these ciphers off by default. When you are doing FIPS, you're going to be specifying a cipher set anyway, so it's better to just document what that will be, and make sure it works.

**Comment by xaleeks** [comment]
FIPS is too much for default for OSS I agree.  So how do we provide a mechanism that allows FIPS to be kept off in OSS but the default in TKG, without having to maintain two code bases.  So can we leverage the configurable cipher suites capability to not only provide granularity at the cipher suite level but also just turn FIPS on / off as a profile.  

I'm kinda just throwing ideas out at this point.  Beware that the FIPS requirement is a long term thing for all future releases within TKG.  So maintaining two Contours would be very heavy

**Comment by youngnick** [comment]
In terms of actual FIPS compliance, it seems to me like there are two requirements:
- Cipher suite must only have FIPS ciphers (basically, something like this PR)
- Go crypto libraries must only use FIPS-certified versions. We can actually do this with a separte Dockerfile using `FROM goboring/golang:<version>` instead of the current Dockerfile. So we may be able to make this relatively easy.

Then, we do not have to maintain two codebases anywhere. But we should talk more about this on #2878.

Thanks for this work, @sunjayBhatia, but I think we should close this PR out.

**Comment by sunjayBhatia** [comment]
Sounds good to me I mostly wanted to start the conversation and capture opinions etc. I figured there would be some reticence to pulling more ciphers out etc.! I think your comments on this and the linked FIPS issue are spot on

**Pull request closed without merging**
