### PR TITLE
test/e2e: Add race detection in e2e tests

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Compile contour binary with -race flag and look for "DATA RACE" in stderr. Fails test if found.

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Looks like logrusr has a race in the version we're on, looks like it might be fixed here but have to check: https://github.com/bombsimon/logrusr/commit/8a325637175b8f219d9f033745cc47e21f06cd67

**Comment by sunjayBhatia** [comment]
Curious if others think we should run this on every e2e run, or just run it as one of the daily build runs cc @projectcontour/maintainers

**Comment by sunjayBhatia** [comment]
> Looks like logrusr has a race in the version we're on, looks like it might be fixed here but have to check: [bombsimon/logrusr@8a32563](https://github.com/bombsimon/logrusr/commit/8a325637175b8f219d9f033745cc47e21f06cd67)

looks like most are fixed by bumping logrusr (will do in a separate PR), though there is another race from our own code it seems

**Comment by clayton-gonsalves** [comment]
+1 to running it on every e2e run and failing PRs if there is a race condition

**Comment by sunjayBhatia** [comment]
running locally found another data race:
```
  ==================                                                                                                                                                                                                                [220/1231]
  WARNING: DATA RACE
  Read at 0x00c0005b3d48 by goroutine 176:
    github.com/projectcontour/contour/internal/xdscache.(*SnapshotHandler).newSnapshotVersion()
        /home/sunjayb/workspace/contour/internal/xdscache/snapshot.go:105 +0x5c
    github.com/projectcontour/contour/internal/xdscache.(*SnapshotHandler).generateNewSnapshot()
        /home/sunjayb/workspace/contour/internal/xdscache/snapshot.go:78 +0x48
    github.com/projectcontour/contour/internal/xdscache.(*SnapshotHandler).OnChange()
        /home/sunjayb/workspace/contour/internal/xdscache/snapshot.go:71 +0x2e
    github.com/projectcontour/contour/internal/dag.ComposeObservers.func1()
        /home/sunjayb/workspace/contour/internal/dag/dag.go:54 +0x85
    github.com/projectcontour/contour/internal/dag.ObserverFunc.OnChange()
        /home/sunjayb/workspace/contour/internal/dag/dag.go:44 +0x3b
    github.com/projectcontour/contour/internal/contour.(*RebuildMetricsObserver).OnChange()
        /home/sunjayb/workspace/contour/internal/contour/metrics.go:92 +0x1ac
    github.com/projectcontour/contour/internal/contour.(*EventHandler).rebuildDAG()
        /home/sunjayb/workspace/contour/internal/contour/handler.go:245 +0x8d
    github.com/projectcontour/contour/internal/contour.(*EventHandler).Start()
        /home/sunjayb/workspace/contour/internal/contour/handler.go:169 +0x4ba
    sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
        /home/sunjayb/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/manager/runnable_group.go:223 +0x1c1
    sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
        /home/sunjayb/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/manager/runnable_group.go:226 +0x47

  Previous write at 0x00c0005b3d48 by goroutine 127:
    github.com/projectcontour/contour/internal/xdscache.(*SnapshotHandler).newSnapshotVersion()
        /home/sunjayb/workspace/contour/internal/xdscache/snapshot.go:110 +0xc4
    github.com/projectcontour/contour/internal/xdscache.(*SnapshotHandler).generateNewSnapshot()
        /home/sunjayb/workspace/contour/internal/xdscache/snapshot.go:78 +0x48
    github.com/projectcontour/contour/internal/xdscache.(*SnapshotHandler).Refresh()
        /home/sunjayb/workspace/contour/internal/xdscache/snapshot.go:66 +0x2e
    github.com/projectcontour/contour/internal/contour.ComposeObservers.func1()
        /home/sunjayb/workspace/contour/internal/contour/observer.go:37 +0x76
    github.com/projectcontour/contour/internal/contour.ObserverFunc.Refresh()
        /home/sunjayb/workspace/contour/internal/contour/observer.go:27 +0x33
    github.com/projectcontour/contour/internal/xdscache/v3.(*EndpointsTranslator).OnDelete()
        /home/sunjayb/workspace/contour/internal/xdscache/v3/endpointstranslator.go:417 +0x1e1
    github.com/projectcontour/contour/internal/contour.(*EventRecorder).OnDelete()
        /home/sunjayb/workspace/contour/internal/contour/metrics.go:50 +0x7b
    k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/sunjayb/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:979 +0x154
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
        /home/sunjayb/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226 +0x48
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
        /home/sunjayb/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227 +0xce
    k8s.io/apimachinery/pkg/util/wait.JitterUntil()
        /home/sunjayb/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204 +0x10d
    k8s.io/apimachinery/pkg/util/wait.Until()
        /home/sunjayb/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:161 +0x78
    k8s.io/client-go/tools/cache.(*processorListener).run()
        /home/sunjayb/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:968 +0x35
    k8s.io/client-go/tools/cache.(*processorListener).run-fm()
        <autogenerated>:1 +0x39
    k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /home/sunjayb/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:72 +0x73
```

**Comment by sunjayBhatia** [comment]
confirmed by https://github.com/projectcontour/contour/actions/runs/6460929135/job/17540262579

**Comment by sunjayBhatia** [comment]
see https://github.com/projectcontour/contour/pull/5819 for a fix

**Comment by sunjayBhatia** [comment]
all observed data races so-far have been fixed now and this branch rebased on `main`, can run a few more times through CI to see if we catch anything else before merging

**Review by skriss — APPROVED** [review]

**Pull request merged**
