### PR TITLE
Set per_connection_buffer_limit_bytes to 32768 as a default

### PR DESCRIPTION
**Pull request by rajatvig**
Fixes part 1 of https://github.com/projectcontour/contour/issues/5264

### CODE REVIEW

**Comment by rajatvig** [comment]
> Looks good to me! 👍
> 
> One question: This might be unnecessary worry, but since there is quite a difference from the original defaults, is there a chance that some users would need the configurability from day one to avoid abrupt change? BTW the same question applies to #5330, and possibly it was the concern that @skriss had in mind here [#5330 (comment)](https://github.com/projectcontour/contour/pull/5330#issuecomment-1548526162)

I can follow it up with an option to configure it using the contour configuration. Was planning to work on https://github.com/projectcontour/contour/issues/1795 as well which I assume would also need defaults to match what exists and overrides where desired.

**Comment by tsaarni** [comment]
> I can follow it up with an option to configure it using the contour configuration.

Sounds great, thank you!

> Was planning to work on #1795 as well which I assume would also need defaults to match what exists and overrides where desired.

Nice! I'll add comment to that issue about some potential Envoy & HTTP/2 TLS issues to look for, that I did not see mentioned/linked so far.

**Review by tsaarni — APPROVED** [review]

**Comment by rajatvig** [comment]
@tsaarni I worked on making it configurable and realised it might be a cleaner implementation and avoids surprises vs setting a default and then adding in configuration.

https://github.com/projectcontour/contour/pull/5493 is the PR.

**Comment by rajatvig** [comment]
Closing in favour of https://github.com/projectcontour/contour/pull/5493

**Pull request closed without merging**
