### PR TITLE
Bugfender is using contour

### PR DESCRIPTION
**Pull request by jgimenez**
[Bugfender](https://bugfender.com) is an adopter of Contour. Submitting a pull request following your instructions here: https://projectcontour.io/resources/adopters/

Let me know if you need anything else!

### CODE REVIEW

**Comment by skriss** [comment]
Thanks @jgimenez! Would you be interested in adding a brief write-up to https://github.com/projectcontour/contour/blob/main/site/content/resources/adopters.md as well?

**Comment by jgimenez** [comment]
Sure, will do!

**Comment by jgimenez** [comment]
Here's, the write-up. I hope you like it!

**Review by sunjayBhatia — COMMENTED** [review]
Hey @jgimenez if you could repush your commits with a signoff (`git commit --signoff`) that should get CI passing and ready to merge!

**Review by skriss — APPROVED** [review]
LGTM; however the logo does appear a little small on the page (see https://deploy-preview-6293--projectcontour.netlify.app/resources/adopters/), if you wanted to edit the image to remove some of the padding above/below, it might look a little better.

Thanks for being part of the community! 🙏

**Comment by skriss** [comment]
> Thanks for the feedback @skriss . Indeed, it looked rather small. Now it's better.

Yep, looks great now!

**Review by skriss — APPROVED** [review]

**Pull request merged**
