### PR TITLE
Edited to comply with yamllint

### LINKED ISSUE #1543: make yamllint target needs to pass
YAML is a mess. As Rob Pike put it "semantic whitespace is a profound mistake". But it's what we have.

I recently added a `make yamllint` target. It would be great if we could make it part of CI for the 1.0 release.

TODO:
- [ ] tweak `.yamllint` configuration, choose reasonable settings that aline with the generally accepted style of Kubernetes YAML.
- [ ] make the `make yamllint` target pass cleanly either by addressing its errors or adjusting `.yamllint`. Blindly following yamllint's complaints is not the goal.
- [ ] add `yamllint` target to `make check`
- [ ] ensure `yamllint` target can fail the build.

### PR DESCRIPTION
**Pull request by ffahri**
Fixes #1543

Signed-off-by: Fahri Yardımcı f.yardimci06@gmail.com

Editing yaml to comply with yamllint also added
yamllint to make check. Travis can check and fail if
yamllint finds any error

### CODE REVIEW

**Comment by ffahri** [comment]
if yaml not correctly set ci will fail https://travis-ci.org/projectcontour/contour/builds/591854275?utm_source=github_status&utm_medium=notification

**Comment by davecheney** [comment]
THiS IS GREAT! Thank you for working on this!

I'm delighted to accept this as is, but in order to avoid world war YAML I'm going to defer to @stevesloka and @youngnick to give their thumbs up as well.

**Comment by youngnick** [comment]
Now, there will be no more world war YAML. What yamllint says goes, goes.

**Comment by stevesloka** [comment]
Thanks @ffahri!

**Pull request merged**
