### PR TITLE
internal/provisioner: set nodePort for LoadBalancerServicePublishingType

### PR DESCRIPTION
**Pull request by izturn**
Signed-off-by: Gang Liu <gang.liu@daocloud.io>

### CODE REVIEW

**Comment by izturn** [comment]
I'd like to set the specific node port for the service instead of generate it by random

**Comment by izturn** [comment]
@skriss  any advise about this use case?

**Review by sunjayBhatia — COMMENTED** [review]
We don't have a good way to represent both the "outside" port and node ports in play here (where "outside" is the port a cloud provider will configure a load balancer to listen on) since the Gateway Listener only gives us one port to specify

I don't think it makes a whole lot of sense to put NodePort configuration in the GatewayClass params object, since that is cluster-scoped and would require some coordination between ports on the Gateway as well

This idea is something that maybe needs to be brought up in a discussion/issue upstream

**Comment by izturn** [comment]
@sunjayBhatia got it, thx

**Pull request closed without merging**
