### PR TITLE
Update Gateway API to 0.6.0-rc2

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Unfortunately includes a bump to controller-runtime and k8s API etc. since Gateway API bumped those as dependencies as well.

Can split them off into their own PRs if we need to.

### CODE REVIEW

**Comment by skriss** [comment]
LGTM once lint errors are addressed

**Comment by sunjayBhatia** [comment]
ah looks like might be blocked on https://github.com/projectcontour/contour/pull/4937

**Comment by skriss** [comment]
Found https://github.com/kubernetes/kubernetes/pull/114585 upstream, so maybe we'll get an upstream patch for this

I guess if we have to we could hack our `generate-crds` step to insert the needed YAML patch..

**Comment by sunjayBhatia** [comment]
> Found [kubernetes/kubernetes#114585](https://github.com/kubernetes/kubernetes/pull/114585) upstream, so maybe we'll get an upstream patch for this
> 
> I guess if we have to we could hack our `generate-crds` step to insert the needed YAML patch..

oh sweet good find, yeah might have to do that in the meantime

**Comment by skriss** [comment]
> > Found [kubernetes/kubernetes#114585](https://github.com/kubernetes/kubernetes/pull/114585) upstream, so maybe we'll get an upstream patch for this
> > I guess if we have to we could hack our `generate-crds` step to insert the needed YAML patch..
> 
> oh sweet good find, yeah might have to do that in the meantime

Yeah that works for me for now and we'll keep an eye on the upstream PR

**Review by skriss — APPROVED** [review]

**Pull request merged**
