### PR TITLE
Update team.html

### PR DESCRIPTION
**Pull request by pnbrown**
Move Steve to Tech Lead and Nick Young to Emeritus Maintainer.

### CODE REVIEW

**Review by tsaarni — APPROVED** [review]
Looks good to me! 

One question: I assume it was agreed that Nick is not removed from the web site? I ask, because there have been cases before where emeritus maintainers were "moved" to this file from the web page https://github.com/projectcontour/community/blob/main/MAINTAINERS.md

**Review by sunjayBhatia — COMMENTED** [review]
yeah @tsaarni has a point about keeping the front page for active maintainers

fine with either way, but if we want to keep emeritus maintainers here we probably should bring back others, probably easier to leave the emeritus maintainers in the community repo

**Comment by skriss** [comment]
+1, I think we can drop Nick here for consistency since he's still listed in the community repo.

**Comment by pnbrown** [comment]
Understood. That change is made.

**Review by skriss — APPROVED** [review]

**Pull request merged**
