### PR TITLE
site: Add docs for header manipualtion with Ingress

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Fixes: #4102

### CODE REVIEW

**Review by skriss — COMMENTED** [review]
Changes LGTM, however while reviewing I couldn't find a link to this page in the TOC - am I missing it? If it's not there, we should add, otherwise I'm not sure how folks find this page.

**Comment by sunjayBhatia** [comment]
> Changes LGTM, however while reviewing I couldn't find a link to this page in the TOC - am I missing it? If it's not there, we should add, otherwise I'm not sure how folks find this page.

no i think i forgot to add it when i added this page, adding now

**Review by skriss — APPROVED** [review]
LGTM

**Comment by skriss** [comment]
Looks like this page needs an update for recently-merged #4271 too, I'll put a PR up for that.

**Review by youngnick — APPROVED** [review]

**Pull request merged**
