### PR TITLE
internal/dag: Set SNI on upstream externalName type clusters for TCPProxy

### PR DESCRIPTION
**Pull request by stevesloka**
Sets the SNI on any TCPProxy.Service which references an externalName type service
as well as having the upstream protocol of "tls".

Updates #2517

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by stevesloka** [comment]
//cc @moderation

**Review by skriss — APPROVED** [review]
This looks OK to me. It'd be nice to have an integration test case for this too.

**Review by sunjayBhatia — COMMENTED** [review]
> This looks OK to me. It'd be nice to have an integration test case for this too.

thinking out loud how this might work, maybe deploy a TLS echo app/service and an external name service that points to it, and use the SNI enforcement endpoint to check it works

**Review by youngnick — APPROVED** [review]
LGTM, and agree that some integration testing around this would be great.

**Comment by skriss** [comment]
needs a rebase

**Comment by skriss** [comment]
@stevesloka I got https://github.com/projectcontour/contour/pull/3342 merged, hopefully that helps with adding a test for this. Happy to walk through it if you want.

**Review by skriss — APPROVED** [review]
OK with me to merge this now and file a follow-up for an integration test.

**Pull request merged**
