### PR TITLE
site: Bump Hugo to 0.119.0

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Also implement more consistent toml file indenting for readability

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Not sure if this will fix the `Mixed content - projectcontour` not being run, but at least an update that is probably overdue for the site

**Review by skriss — APPROVED** [review]
clicked around the preview site a bit, LGTM

**Comment by sunjayBhatia** [comment]
Added @pnbrown as a reviewer in case you wanted to check out the site deploy preview before we update (should be a no-op but just in case): https://deploy-preview-5795--projectcontour.netlify.app/

**Comment by pnbrown** [comment]
Will do

**Comment by sunjayBhatia** [comment]
Planning on merging today unless anyone has comments/finds bugs in the site 👍🏽

**Comment by pnbrown** [comment]
I haven't seen anything

**Comment by skriss** [comment]
:shipit:

**Pull request merged**
