### PR TITLE
Update dag.go

### PR DESCRIPTION
**Pull request by hxysayhi**
Corrected typo in related comments of cluster struct

### CODE REVIEW

**Review by sunjayBhatia — APPROVED** [review]
Thanks!

**Comment by skriss** [comment]
@hxysayhi you'll need to add DCO signoff to your commit, see https://github.com/projectcontour/contour/pull/4795/checks?check_run_id=8923431594 for details.

**Comment by skriss** [comment]
@hxysayhi are you able to resolve the above feedback so we can get this merged? Thanks!

**Comment by hxysayhi** [comment]
> @hxysayhi are you able to resolve the above feedback so we can get this merged? Thanks!

Thanks for your feedback, I have fixed the existing problem.

**Pull request merged**
