### PR TITLE
update Envoy to 1.25.1

### PR DESCRIPTION
**Pull request by skriss**

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
image looks like it is up on docker hub, rerunning CI

**Review by sunjayBhatia — APPROVED** [review]

**Comment by sunjayBhatia** [comment]
@skriss do you want to cherry-pick this to release-1.24 or merge `main` over to that branch? (since the delta is pretty small, includes dependency updates but no other security patches as far as i can tell)

**Comment by skriss** [comment]
> @skriss do you want to cherry-pick this to release-1.24 or merge main over to that branch? (since the delta is pretty small, includes dependency updates but no other security patches as far as i can tell, but does have CRD changes at least for the controller-tools annotation etc.)

I was thinking cherry-pick if that works for you, since nothing else looks security-related.

**Comment by sunjayBhatia** [comment]
> > @skriss do you want to cherry-pick this to release-1.24 or merge main over to that branch? (since the delta is pretty small, includes dependency updates but no other security patches as far as i can tell, but does have CRD changes at least for the controller-tools annotation etc.)
> 
> I was thinking cherry-pick if that works for you, since nothing else looks security-related.

LGTM

**Pull request merged**
