### PR TITLE
apis/projectcontour: replace copied Conditions structs with aliases

### LINKED ISSUE #3003: Replace v1.Condition with Kubernetes metav1.Condition
**Please describe the problem you have**

To adopt the standardized Condition struct, we copied `metav1.Condition` into the Contour API. Once we (and all consumers of the Contour API package) upgrade to client-go >= 0.19, we can replace the copy with an alias to `metav1.Condition`.

### PR DESCRIPTION
**Pull request by skriss**
Replaces the copy-pasted Conditions struct and related types with
aliases to the k8s.io/apimachinery/pkg/apis/meta/v1 types now that
Contour depends on a sufficiently new version of it.

Closes #3003.

Signed-off-by: Steve Kriss <krisss@vmware.com>

@stevesloka @youngnick @jpeach I think this works for retaining compatibility while removing the copy-paste, but let me know if I'm missing anything. Also, is there any reason we can't yet make this change (ref. #3003)?

### CODE REVIEW

**Review by stevesloka — APPROVED** [review]
/lgtm

**Comment by skriss** [comment]
@jpeach @youngnick would appreciate your input on this one too.

**Comment by jpeach** [comment]
> @jpeach @youngnick would appreciate your input on this one too.

Yeh this looks good to me too.

**Comment by skriss** [comment]
I'll merge tomorrow if I haven't heard anything further from @youngnick.

**Pull request merged**
