### PR TITLE
cmd/contour: allow Kube client QPS/burst configuration

### PR DESCRIPTION
**Pull request by skriss**
Allows the Kubernetes client's QPS and burst
to be configured for the contour serve command.

Signed-off-by: Steve Kriss <krisss@vmware.com>

Still doing some testing with this but might be nice to include in 1.24 to see if it helps with scale issues.

### CODE REVIEW

**Comment by skriss** [comment]
Interesting, found https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/config#GetConfig -- looks like controller-runtime defaults these to 20/30 instead of the 5/10 that client-go uses.

**Comment by skriss** [comment]
Quick ad-hoc test confirms that these flags are working and make a difference. I created 10 HTTPProxies at once and observed the timestamps of their updates (note there are 20 updates total because each one gets status.ingress and status.conditions set separately):

1. With default QPS/burst settings, takes nearly 2 seconds to get through all updates:

```
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.613463" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.616942" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.620470" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.623878" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.626612" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.632019" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.635534" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.639589" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.642808" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.646583" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.649964" context=StatusUpdateHandler
time="2023-01-25T19:55:26Z" level=info msg="Updating resource at Jan 25 19:55:26.818779" context=StatusUpdateHandler
time="2023-01-25T19:55:27Z" level=info msg="Updating resource at Jan 25 19:55:27.024993" context=StatusUpdateHandler
time="2023-01-25T19:55:27Z" level=info msg="Updating resource at Jan 25 19:55:27.222049" context=StatusUpdateHandler
time="2023-01-25T19:55:27Z" level=info msg="Updating resource at Jan 25 19:55:27.418763" context=StatusUpdateHandler
time="2023-01-25T19:55:27Z" level=info msg="Updating resource at Jan 25 19:55:27.623177" context=StatusUpdateHandler
time="2023-01-25T19:55:27Z" level=info msg="Updating resource at Jan 25 19:55:27.822516" context=StatusUpdateHandler
time="2023-01-25T19:55:28Z" level=info msg="Updating resource at Jan 25 19:55:28.024864" context=StatusUpdateHandler
time="2023-01-25T19:55:28Z" level=info msg="Updating resource at Jan 25 19:55:28.221517" context=StatusUpdateHandler
time="2023-01-25T19:55:28Z" level=info msg="Updating resource at Jan 25 19:55:28.420659" context=StatusUpdateHandler
```

2. With QPS=20, burst=30, takes under half a second:

```
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.704255" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.709776" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.712717" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.715430" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.718053" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.722608" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.726199" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.730188" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.735980" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.740747" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.744238" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.845356" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.849038" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.851939" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.855219" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.857822" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.860963" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.863600" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.866590" context=StatusUpdateHandler
time="2023-01-25T19:56:45Z" level=info msg="Updating resource at Jan 25 19:56:45.869894" context=StatusUpdateHandler
```

**Comment by skriss** [comment]
This would only be relevant for #5001 if there are lots of updates queued at once, but still likely a helpful knob to have for some clusters.

**Review by sunjayBhatia — COMMENTED** [review]
Given we kinda need to configure this via flag/ConfigMap to suit different use cases I'm on the fence now about eventually moving to the ContourConfiguration CRD, seems like a hassle to add more CLI flags which we have to do since this one in particular doesn't really work to put as a field on a resource we have to fetch from the API server, WDYT?

**Comment by sunjayBhatia** [comment]
(implementation looks good, like the logging bit that lets us know what it is configured to, nice to see)

**Comment by skriss** [comment]
> Given we kinda need to configure this via flag/ConfigMap to suit different use cases I'm on the fence now about eventually moving to the ContourConfiguration CRD, seems like a hassle to add more CLI flags which we have to do since this one in particular doesn't really work to put as a field on a resource we have to fetch from the API server, WDYT?

Yeah, I was having similar thoughts as I went through this and realized where it needed to go. Definitely something for us to revisit and see if it still makes sense.

**Review by sunjayBhatia — APPROVED** [review]

**Comment by skriss** [comment]
@sunjayBhatia are you OK with merging this now for inclusion in 1.24? Just wanted to check since we've already cut the RC.

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia are you OK with merging this now for inclusion in 1.24? Just wanted to check since we've already cut the RC.

sounds good to me, the default behavior should be the same so lower risk

**Pull request merged**
