### PR TITLE
internal/dag: set Gateway Listener conditions

### LINKED ISSUE #3529: Gateway API: Listener Route binding selector kind must match Routes compatible with Listener protocol
The `kind` field of the route binding selector has the following description:

```
Kind is the kind of the route resource to select.

Kind MUST correspond to kinds of routes that are compatible with the application protocol specified in the Listener’s Protocol field.

If an implementation does not support or recognize this resource type, it SHOULD set the “ResolvedRefs” condition to false for this listener with the “InvalidRoutesRef” reason.
```

The `protocol` field is defined as:

```
Protocol specifies the network protocol this listener expects to receive. The GatewayClass MUST apply the Hostname match appropriately for each protocol:

- For the “TLS” protocol, the Hostname match MUST be applied to the SNI server name offered by the client.
- For the “HTTP” protocol, the Hostname match MUST be applied to the host portion of the effective request URI or the :authority pseudo-header
- For the “HTTPS” protocol, the Hostname match MUST be applied at both the TLS and HTTP protocol layers.
```

- [x] Process Kind
- [ ] Set status on Gateway

See: https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.Listener

### LINKED ISSUE #4124: Gateway API: implement ListenerStatus for Gateways
ref. https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayStatus

We need to populate the `gateway.status.listeners` field with supported kinds, # of attached routes, listener-specific conditions, etc.

### LINKED ISSUE #4180: Gateway API: Gateway does not set `InvalidCertificateRef` status for non-existent secret
**What steps did you take and what happened:**

#### 2. Deploy Gateway with non-existent secret

- For example, Gateway with the secret `ingress-conformance-tls-arjanhco-foo` which does not exist.

```
$ kubectl  -n contour-external-tls  get gateway ingress-conformance-tls-jemmfrbg  -o yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  creationTimestamp: "2021-11-15T07:28:05Z"
  generation: 4
  name: ingress-conformance-tls-jemmfrbg
  namespace: contour-external-tls
  resourceVersion: "8554"
  uid: aa35f4b0-a89a-4de2-bbca-f9f1a5827411
spec:
  gatewayClassName: contour-external-tls
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: https-test
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: ingress-conformance-tls-arjanhco-foo
      mode: Terminate
status:
  conditions:
  - lastTransitionTime: "2021-11-15T07:36:09Z"
    message: Valid Gateway
    observedGeneration: 4
    reason: Valid
    status: "True"
    type: Ready
```

#### Check the status

The contour pod logs prints the `Secret not found`:

```
$ kubectl  -n contour-external-tls  logs contour-7d56bbcd4f-x867p
  ...
time="2021-11-15T07:35:58Z" level=error msg="Spec.VirtualHost.TLS Secret \"ingress-conformance-tls-arjanhco-foo\" is invalid: Secret not found" context=GatewayAPIProcessor
```

but the status becomes `Ready`.

```
$ kubectl  -n contour-external-tls  get gateway ingress-conformance-tls-jemmfrbg 
NAME                               CLASS                  ADDRESS   READY   AGE
ingress-conformance-tls-jemmfrbg   contour-external-tls             True    71m
```

**What did you expect to happen:**

- The Gateway gets the `InvalidCertificateRef` status.

**Environment:**

Contour installed via the yaml (2021/Nov/15):

```
CONTOUR_OPERATOR_VERSION="main" # This is for controlling which version of contour-operator we want to use.
YAML_URL="https://raw.githubusercontent.com/projectcontour/contour-operator/${CONTOUR_OPERATOR_VERSION}/examples/operator/operator.yaml"
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-19T11:52:07Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T20:01:24Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by skriss**
Sets various Listener conditions according to
the Gateway API v1alpha2 spec. Also sets the
Gateway "Ready" condition to false if there
are invalid listeners.

Closes #3529.
Closes #4180.
Closes #4124.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
Using the "hide whitespace" option on the diff will help a lot here.

**Review by sunjayBhatia — APPROVED** [review]
LGTM!

only addition would be to add a test somewhere to confirm that listener condition messages are appended if there are multiple issues, implementation looks good 👍🏽

**Comment by skriss** [comment]
> LGTM!
> 
> only addition would be to add a test somewhere to confirm that listener condition messages are appended if there are multiple issues, implementation looks good 👍🏽

Good call, added a simple unit test for that method.

**Review by youngnick — APPROVED** [review]
LGTM, this looks great, thanks @skriss!

**Pull request merged**
