### PR TITLE
ci: Add envoyproxy.io to ignore list for site-proof check

### PR DESCRIPTION
**Pull request by stevesloka**
The site proof check which runs on each run checks for invalid links, however, the links
to envoyproxy.io seem to fail the site check. This adds the envoyproxy.io site to the ignore
list which will skip this site from getting checked.

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Review by abhide — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Review by sunjayBhatia — APPROVED** [review]
This is a tricky one b/c Envoy doc links would be bad to not catch if they're legitimately broken

LGTM though maybe we should file an issue to try to fiddle with the siteproof params so we don't skip as many sites or at least can craft config that lets us still check Envoy

**Comment by skriss** [comment]
> This is a tricky one b/c Envoy doc links would be bad to not catch if they're legitimately broken
> 
> LGTM though maybe we should file an issue to try to fiddle with the siteproof params so we don't skip as many sites or at least can craft config that lets us still check Envoy

Agreed. Also, we should keep in mind we may be moving to Hugo in the near future, so perhaps our tooling will change.

**Comment by sunjayBhatia** [comment]
> > This is a tricky one b/c Envoy doc links would be bad to not catch if they're legitimately broken
> > LGTM though maybe we should file an issue to try to fiddle with the siteproof params so we don't skip as many sites or at least can craft config that lets us still check Envoy
> 
> Agreed. Also, we should keep in mind we may be moving to Hugo in the near future, so perhaps our tooling will change.

https://github.com/projectcontour/contour/issues/3384

**Comment by skriss** [comment]
Merging as-is, no risk of conflict.

**Pull request merged**
