### PR TITLE
Fix bunch of typos

### PR DESCRIPTION
**Pull request by invidian**
Found using Codespell with the following command:

codespell -S .git,*.png,*.woff,*.ttf,*.jpg,*.ico -L \
keypair,keypairs,nd,suh,od,rouge,als,wit

Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>

### CODE REVIEW

**Comment by stevesloka** [comment]
Thanks so much for this @invidian! A neat follow up would be to upgrade our current spellcheck task in the Makefile as it seems it's not doing its job at the moment.

**Review by stevesloka — APPROVED** [review]
/lgtm

**Comment by invidian** [comment]
>Thanks so much for this @invidian! A neat follow up would be to upgrade our current spellcheck task in the Makefile as it seems it's not doing its job at the moment.

I'll have a look later :wink: Would you like it in this PR or separate?

**Comment by stevesloka** [comment]
> Would you like it in this PR or separate?

I think a separate would be fine, thanks!

**Comment by invidian** [comment]
Rebased and created #3110 to replace `misspell` with `codespell`.

**Comment by skriss** [comment]
LGTM, thanks for rebasing this on the 1.10 docs!

**Pull request merged**
