### PR TITLE
build: apply standard Docker image labels

### LINKED ISSUE #2392: Add release metadata to the released Docker images
There's no way to cross-check the Docker images we release against the source code that it was built from. We should add Docker labels that tracks release metadata.

The OCI spec defines a set of standard labels and these seem to be in use by many projects:

https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys

We should add:

| Label | Content |
| - | - |
| org.opencontainers.image.created | timestamp |
| org.opencontainers.image.url |  Link to github release notes? |
| org.opencontainers.image.documentation | Link to docs |
| org.opencontainers.image.source | Link to GitHub tarball download? |
| org.opencontainers.image.version | Release tag name |
| org.opencontainers.image.revision| Full git SHA |
| org.opencontainers.image.vendor | ??? |
| org.opencontainers.image.licenses | SPDX apache2 |
| org.opencontainers.image.title | Contour |
| org.opencontainers.image.description | descriptive text |

### PR DESCRIPTION
**Pull request by jpeach**
Apply Docker image labels standardized in the OCI container image spec.
This improves our ability to trace the provenance of a Contour image
back to the corresponding source code.

This fixes #2392.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
```
$ make container
...
Successfully tagged projectcontour/contour:v1.2.0-91-g7696eb2
$ docker inspect projectcontour/contour:v1.2.0-91-g7696eb2
...
            "Labels": {
                "org.opencontainers.image.created": "2020-03-30T04:46:32+0000",
                "org.opencontainers.image.description": "High performance ingress controller for Kubernetes",
                "org.opencontainers.image.documentation": "https://projectcontour.io/",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "7696eb2a6ab51cd0f2d2c1f08086b3c927ba3be6",
                "org.opencontainers.image.source": "https://github.com/projectcontour/contour/archive/v1.2.0-91-g7696eb2.tar.gz",
                "org.opencontainers.image.title": "Contour",
                "org.opencontainers.image.url": "https://projectcontour.io/",
                "org.opencontainers.image.vendor": "Project Contour",
                "org.opencontainers.image.version": "v1.2.0-91-g7696eb2"
            }
...
```

**Comment by pickledrick** [comment]
LGTM

**Comment by jpeach** [comment]
> Overall looks pretty cool! One thing I noticed is the image url points to `projectcontour.io`. Should that be something like `docker.io/projectcontour/contour`?
> 
> ```
> "org.opencontainers.image.url": "https://projectcontour.io/",
> ```

The OCI spec documents this field as "URL to find more information on the image". When I read this, I thought it meant more information about the software that ships in the image, but I can see that it can also be read as more information about the image that the software ships in.

If it's the image, then we could go with `https://hub.docker.com/r/projectcontour/contour`.

The original [label-schema](http://label-schema.org/rc1/#label-semantics) definition of this field is:

> URL of website with more information about the product or service provided by the container.

This is a lot clearer and would support the first interpretation.

**Comment by youngnick** [comment]
It probably doesn't matter too much, but tend to agree that just the projectcontour page sounds like the info it's intended for.

**Comment by jpeach** [comment]
@stevesloka WDYT?

**Pull request merged**
