### PR TITLE
Parameterize Docker image build to enable building with different base images

### PR DESCRIPTION
**Pull request by sunjayBhatia**
This will enable keen users who can build Contour themselves to use a different golang image to support building with FIPS-validated BoringCrypto library.

- Allow base golang image to be swapped
- CGO is required for linking with BoringCrypto
- Add ability to pass more linker flags to ensure a static build
- Ensures we use the net and os/user packages from Go not libc

Updates https://github.com/projectcontour/contour/issues/2878

### CODE REVIEW

**Review by skriss — APPROVED** [review]
LGTM pending CI

**Review by youngnick — APPROVED** [review]
LGTM pending CI as well.

**Review by stevesloka — APPROVED** [review]

**Comment by sunjayBhatia** [comment]
checking integration tests pass when using the `goboring/golang` image and enabling CGO

**Comment by sunjayBhatia** [comment]
> checking integration tests pass when using the `goboring/golang` image and enabling CGO

Actually please hold on merging this since when CGO is enabled the `scratch` base image we export `contour` to won't work

**Comment by sunjayBhatia** [comment]
Need some more flags to make the binary fully static when we enable CGO for linking against the BoringCrypto libraries

**Comment by sunjayBhatia** [comment]
To build a contour image with BoringCrypto using this change you would run:

```
make container BUILD_BASE_IMAGE=rancher/hardened-build-base:v1.15.8b5 BUILD_CGO_ENABLED=1 BUILD_EXTRA_GO_LDFLAGS="-linkmode=external -extldflags=-static"
```

The `rancher/hardened-build-base:v1.15.8b5` or some equivalent that has static BoringCrypto libraries is used in place of `goboring/golang:1.15.8b5` which has dynamic libraries + libc gets linked dynamically, preventing us from providing contour just on top of a scratch image

**Review by skriss — APPROVED** [review]

**Review by stevesloka — APPROVED** [review]

**Pull request merged**
