### PR TITLE
site: Update Envoy extensions list required by Contour

### PR DESCRIPTION
**Pull request by stevesloka**
Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
Were you able to test a custom build with just this list of extensions compiled in?

**Review by skriss — APPROVED** [review]
LGTM by inspection, but haven't independently verified that it's the minimal necessary list.

**Comment by stevesloka** [comment]
> Were you able to test a custom build with just this list of extensions compiled in?

Yup! That's what took this so long, I did a bunch of testing. If you want to run through it in your cluster that might be a good double check. My image is: `stevesloka/envoy:v1.16.1.contour`

**Comment by skriss** [comment]
> > Were you able to test a custom build with just this list of extensions compiled in?
> 
> Yup! That's what took this so long, I did a bunch of testing. If you want to run through it in your cluster that might be a good double check. My image is: `stevesloka/envoy:v1.16.1.contour`

Nice! Sure I'll try it out.

**Comment by skriss** [comment]
Everything looks good to me, ran integration tests and poked around a bit.

**Pull request merged**
