### PR TITLE
internal/controller: trigger reconciles when elected leader

### PR DESCRIPTION
**Pull request by skriss**
Triggers reconciles of all GatewayClasses and
Gateways when a Contour pod is elected leader,
to ensure that their statuses are up-to-date.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
Seemed to work well with manual testing, still need to verify with the Operator example test

**Comment by skriss** [comment]
Was able to get this running locally with the operator tests, and confirm that it now passes those tests.

**Review by youngnick — APPROVED** [review]
LGTM, with the testing, did you mean this fixes some failing operator tests?

**Comment by skriss** [comment]
> LGTM, with the testing, did you mean this fixes some failing operator tests?

Yeah, the `test-example-linux` operator test has been failing due to this -- it does two consecutive installs of Contour and the second one takes awhile to be elected leader because the leader-elect ConfigMap indicates the original Contour is still leader, so that uncovered this issue. But, I was able to run that test locally with this PR's build of Contour and confirm the issue went away. So hopefully once this merges, Operator CI will go back to (mostly) passing.

**Review by sunjayBhatia — APPROVED** [review]

**Pull request merged**
