### PR TITLE
[release-1.10] Update Contour Docker image to v1.10.1.

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
@skriss I guess this has to be merged before manually making a tag and running the image push so the v1.10.1 image exists?

**Comment by skriss** [comment]
Yeah, I think so...I think this change may usually be pushed directly to the branch, rather than PR'ed.

**Comment by skriss** [comment]
I guess the integration tests won't pass because of the tags, so we'll just have to ignore that check on this PR.

**Review by stevesloka — APPROVED** [review]
/lgtm

**Review by sunjayBhatia — APPROVED** [review]

**Pull request merged**
