### PR TITLE
Add simple debug logging flag

### PR DESCRIPTION
**Pull request by youngnick**
I don't believe that we want to add any more levels than error, info, and debug at this point.

Signed-off-by: Nick Young <ynick@vmware.com>

### CODE REVIEW

**Comment by davecheney** [comment]
I'd rather not see it added to the config file, that implies that people are running all their clusters in debug mode which mean's we haven't put enough effort into making the info level log statements useful.

**Comment by jpeach** [comment]
> I'd rather not see it added to the config file, that implies that people are running all their clusters in debug mode which mean's we haven't put enough effort into making the info level log statements useful.

Since it's not enabled by default, why does it imply that? It's way harder to enable when you have to rewrite command line flags than editing the config.

**Comment by davecheney** [comment]
> It's way harder to enable when you have to rewrite command line flags than editing the config.

I don't agree with this statement, the latter requires me to edit a text file, the former I just type when I want to use it.

**Comment by youngnick** [comment]
I see where you are coming from @jpeach, but for now I think this is mainly for local use.

**Pull request merged**
