### PR TITLE
docs:Delete the link of operator.md

### PR DESCRIPTION
**Pull request by yanggangtony**
image
image

labels: ["release-note/none-required"]

### CODE REVIEW

**Comment by skriss** [comment]
@yanggangtony the Operator is no longer maintained, so these were removed intentionally. Is there a broken link or something else that led you to believe these should exist?

**Comment by skriss** [comment]
Ah I see, the entry in the table of contents still exists. Can you remove it, instead of adding the page back? Thanks

**Comment by yanggangtony** [comment]
@skriss 
Thanks for quick review.
Yes , the table of contents still exists.
I will remove the table links.

**Comment by yanggangtony** [comment]
@skriss 
Rebased.
Hi, Thanks for review.
I have deleted the link in ```site/data/docs/main-toc.yml```.
The ohter relelease version is not necessary , As it is had operator before.

**Review by sunjayBhatia — APPROVED** [review]

**Comment by yanggangtony** [comment]
Thanks.

**Pull request merged**
