### PR TITLE
Updates Examples for Gateway API Support

### PR DESCRIPTION
**Pull request by danehans**
Adds a script and includes the script in the `generate` make target. This is for supporting a Gateway API install experience similar to `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`.

Note that `examples/render/contour-gateway.yaml` was generated from `make generate`.

Requires https://github.com/projectcontour/contour/pull/3659

### CODE REVIEW

**Comment by danehans** [comment]
When reviewing, I suggest [filtering the commits](https://github.com/projectcontour/contour/pull/3664/commits/711bb738c5b0ebd18a45d180923179a560749d43) to separate this PR from https://github.com/projectcontour/contour/pull/3510.

**Comment by stevesloka** [comment]
Hey @danehans, this needs a good rebase then can take a look. I think having Gateway examples is a great idea to get folks started. =)

**Comment by youngnick** [comment]
I think we should try and get this in for 1.16, to help people try out Gateway API functions more easily. I'll add it to milestone + column for now, happy to be overridden here though @xaleeks.

**Comment by danehans** [comment]
> I think we should try and get this in for 1.16, to help people try out Gateway API functions more easily. 

@youngnick note that examples are not useful until the gateway controller is implemented (targeted for v1.17.0).

**Review by youngnick — APPROVED** [review]
LGTM now, thanks @danehans

**Review by stevesloka — APPROVED** [review]

**Pull request merged**
