### PR TITLE
Gateway API: implement HTTP query param matching

### LINKED ISSUE #4089: Gateway API: implement HTTP query param matching [extended]
ref. https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPQueryParamMatch

extended support in v1alpha2.

### PR DESCRIPTION
**Pull request by skriss**
Closes #4089.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Review by sunjayBhatia — COMMENTED** [review]
looks good overall, I think maybe only thing to add would be to check for duplicate requested matches for the same key (and set status accordingly), and maybe offer an e2e test/document how the match will work with Envoy if a URL is presented that has the same query key multiple times (e.g. `/foo?bar=1&bar=2`), since as far as I can tell its server dependent and not in an RFC

**Comment by skriss** [comment]
> looks good overall, I think maybe only thing to add would be to check for duplicate requested matches for the same key (and set status accordingly), 

Good point, I don't see anything in Gateway API right now that specifies behavior, but for HTTP Header matches which are structured similarly, it says:
> If multiple entries specify equivalent header names, only the first entry with an equivalent name MUST be considered for a match. Subsequent entries with an equivalent header name MUST be ignored. Due to the case-insensitivity of header names, “foo” and “Foo” are considered equivalent.

So I think it probably makes sense to apply similar logic here, and I'll raise something upstream to clarify in the spec.

> and maybe offer an e2e test/document how the match will work (match on first occurrence of key, last, etc.) with Envoy if a URL is presented that has the same query key multiple times (e.g. `/foo?bar=1&bar=2`), since as far as I can tell its server dependent and not in an RFC

Good idea, let me test this out.

**Comment by skriss** [comment]
@sunjayBhatia see https://github.com/projectcontour/contour/pull/4588/commits/0fd420f5699962fc34fea7f8e96e893065247c68, let me know if this makes sense to you!

**Review by sunjayBhatia — APPROVED** [review]
looks good!

**Pull request merged**
