### PR TITLE
test/e2e: add test for Gateway with multiple HTTPS listeners

### PR DESCRIPTION
**Pull request by skriss**
Adds a test that demonstrates a Gateway
with multiple HTTPS Listeners, each with
a different hostname and TLS cert.

Also updated some of the Describe text for clarity.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
I have to say, I did not quite realize that this worked this way.

**Comment by sunjayBhatia** [comment]
unrelated flake looks like

**Comment by sunjayBhatia** [comment]
> I have to say, I did not quite realize that this worked this way.

yeah i agree, i never really thought of it like this, makes sense though rereading [this](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.GatewaySpec) and makes sense it works how we implemented it since for each you would add another secure vhost in the dag, and theres no conflicts

**Review by sunjayBhatia — APPROVED** [review]

**Comment by skriss** [comment]
> > I have to say, I did not quite realize that this worked this way.
> 
> yeah i agree, i never really thought of it like this, makes sense though rereading [this](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.GatewaySpec) and makes sense it works how we implemented it since for each you would add another secure vhost in the dag, and theres no conflicts

Yep -- I think we do have some additional validation to do to ensure that all the HTTPS listeners are truly compatible (same port, no conflicting hostnames, etc), but nice that it mostly already works. I guess one way to think about it is that a Gateway API Listener is more akin to an Envoy filter chain, than an Envoy listener.

**Comment by youngnick** [comment]
> I guess one way to think about it is that a Gateway API Listener is more akin to an Envoy filter chain, than an Envoy listener.

In this case, yeah. But sadly, not always. These are examples of _mergeable_ listeners, which act more like HCMs with their own filter set in Envoy terms, and like you said, _mergeable_ listeners have to have no conflicts on a bunch of values. Listeners *can* also be used to describe completely separate ports etc, which would act more like Envoy listeners.

**Review by youngnick — APPROVED** [review]

**Comment by youngnick** [comment]
This seems like something we should probably have upstream conformance tests on too, now that I think about it.

**Comment by skriss** [comment]
> This seems like something we should probably have upstream conformance tests on too, now that I think about it.

Yeah I'd love to contribute a few more of the E2E's that we have upstream, just need to find some time for it. Ultimately it'd be awesome if we could mostly get rid of ours and rely on the conformance tests instead.

**Pull request merged**
