### PR TITLE
site\_guides\cert-manager.md

### LINKED ISSUE #2281: Different names for secret referenced in "Making cert-manager work with HTTPProxy"
**What steps did you take and what happened:**
In the documentation the guide for cert-manager https://projectcontour.io/guides/cert-manager/ gives solution how could we proceed with "Making cert-manager work with HTTPProxy"

The workaround builds on using Ingress object to create Secret which is than consumed by HTTPProxy by referencing the same secret. 

However, example specifies different names for Secret in Ingress and HTTPProxy objects.

```yaml class:"lineNo"
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbinproxy
spec:
  virtualhost:
    fqdn: httpbinproxy.davecheney.com
    tls:
      secretName: httpbin
  routes:
  - services:
    - name: httpbin
      port: 8080
```
``` yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  name: httpbinproxy
  namespace: default
spec:
  rules:
  - host: httpbinproxy.davecheney.com
    http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 8080
  tls:
  - hosts:
    - httpbinproxy.davecheney.com
    secretName: httpbinproxy
```

Ingress creates secretName: **httpbin**, while HTTPProxy defines secretName: **httpbinproxy**.

**What did you expect to happen:**

Both Ingress and HTTPPRoxy should define Secret with same name e.g. secretName: **httpbin**

### PR DESCRIPTION
**Pull request by vukg**
Fixes #2281

Signedoff-by Vuk Gojnic <vuk.gojnic@gmail.com>

### CODE REVIEW

**Comment by davecheney** [comment]
Top tip: the first line of a commit should describe what will happen if it is merged. I suggest

site: fix secret name in certmanager documentation.

On 25 Feb 2020, at 08:33, Vuk Gojnic <notifications@github.com> wrote:

﻿

Fixes #2281<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprojectcontour%2Fcontour%2Fissues%2F2281&data=02%7C01%7Ccheneyd%40vmware.com%7C1f32231a16bc4fcff06008d7b9712cbf%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637181768053023735&sdata=YRUcsAkGMav6LzVJnM5%2FjG8jtChd4WueYYql4CEqsaY%3D&reserved=0>

Signedoff-by Vuk Gojnic vuk.gojnic@gmail.com<mailto:vuk.gojnic@gmail.com>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/projectcontour/contour/pull/2284<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprojectcontour%2Fcontour%2Fpull%2F2284&data=02%7C01%7Ccheneyd%40vmware.com%7C1f32231a16bc4fcff06008d7b9712cbf%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637181768053023735&sdata=RmFdzghLF2KBLCV08036wqpROUYP%2F4JMLr7mdD%2BHYJo%3D&reserved=0>

Commit Summary

  *   site\_guides\cert-manager.md

File Changes

  *   M site/_guides/cert-manager.md<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprojectcontour%2Fcontour%2Fpull%2F2284%2Ffiles%23diff-0&data=02%7C01%7Ccheneyd%40vmware.com%7C1f32231a16bc4fcff06008d7b9712cbf%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637181768053033728&sdata=s%2BTiFayTbYIrAJzqE67yNqZcaa384s5cWbJhqIEhHTw%3D&reserved=0> (4)

Patch Links:

  *   https://github.com/projectcontour/contour/pull/2284.patch<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprojectcontour%2Fcontour%2Fpull%2F2284.patch&data=02%7C01%7Ccheneyd%40vmware.com%7C1f32231a16bc4fcff06008d7b9712cbf%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637181768053033728&sdata=BYJu%2FKGYnBGi8T1NdrFkuldF3E0Uv02kHLar9qRuaQk%3D&reserved=0>
  *   https://github.com/projectcontour/contour/pull/2284.diff<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprojectcontour%2Fcontour%2Fpull%2F2284.diff&data=02%7C01%7Ccheneyd%40vmware.com%7C1f32231a16bc4fcff06008d7b9712cbf%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637181768053033728&sdata=Ciym0XaM7NA81qzMeOpI8vcosVOZBT4QdsIqKvGslCE%3D&reserved=0>

**Comment by stevesloka** [comment]
Hey, @vukg can you look at @davecheney's comment about the commit message? 

Also, you'll need to sign the commit. This could work, then need to re-push:

```
$ git commit --amend --signoff
```

**Comment by vukg** [comment]
@stevesloka it should work now, I pushed amended commit.

**Comment by stevesloka** [comment]
Hey @vukg almost there on getting this merged. Could you rebase the commits together into a single commit? Also on the last one make sure it's signed off? The checker is still not happy about it. =)

Ping me on k8s slack (@stevesloka) if you need any help with the previous steps.

**Comment by stevesloka** [comment]
Hey, @vukg I send you a message on slack but here are the contents as well for reference:

```
$ git fetch upstream (Where upstream is the contour git repo)
$ git rebase -i upstream/master
  Put an r in front of the first commit, and an f in any others
$ git commit --amend --signoff 
$ git push origin cert-manager-guide-correction -f
```

**Comment by vukg** [comment]
Thanks @stevesloka! I did that, but there are still conflicts. If you can resolve them in favor of upstream (I just squashed some other commits in between) that would be great.

**Comment by stevesloka** [comment]
Fixed in #2368

**Pull request closed without merging**
