### PR TITLE
chore: update Envoy to v1.16.1

### PR DESCRIPTION
**Pull request by yoitsro**
Updates Envoy to the latest minor version.

Contains the changes listed here: https://www.envoyproxy.io/docs/envoy/v1.16.1/version_history/current

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
LGTM, thanks for this @yoitsro!

**Comment by stevesloka** [comment]
Thanks for this @yoitsro! If you'd like, it'd be great as well to update the Envoy Matrix including links to the CVEs (https://projectcontour.io/resources/envoy/).

**Comment by yoitsro** [comment]
Hey @stevesloka. I've updated the matrix - it doesn't appear as though there were any CVEs addressed with Envoy 1.16.1.

I've also rebased on top of `main` to take into account the latest changes.

**Comment by jpeach** [comment]
> Hey @stevesloka. I've updated the matrix - it doesn't appear as though there were any CVEs addressed with Envoy 1.16.1.

IIUC, CVEs are supposed to be published later this week.

**Comment by youngnick** [comment]
@yoitsro, just going through PRs, this one needs a rebase for CI to pass, but I also notice you missed the DCO signoff on the final commit. Could you fix that up too please?

**Comment by yoitsro** [comment]
Hey @youngnick. That should be good to go now.

**Review by stevesloka — APPROVED** [review]
/lgtm

**Pull request merged**
