### PR TITLE
internal/envoy: Update GZip to valid wellknown name

### PR DESCRIPTION
**Pull request by stevesloka**
Updates: #2479

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
IIUC, the name can be anything (at least with current Envoy versions); just specifying the typed config is enough envoy do do the right thing.

**Comment by youngnick** [comment]
I don't understand what's happening here. @stevesloka, is this PR just to clear the messages from the Envoy logs? It seems like the better long-term fix is to move the filter config to the typed configs, and to stop using the names altogether?

**Comment by stevesloka** [comment]
@youngnick yes the goal of this is to update the names as the current one's are deprecated and will stop working at some point. 

I'd like to move to the typedconfig, but can't seem to get that to work (with xDS v2 at least): https://github.com/envoyproxy/go-control-plane/pull/354#issuecomment-696801996

For now this bumps it down the road to avoid compatibility issues until we get it sorted out properly.

**Comment by skriss** [comment]
Per [this Slack thread](https://envoyproxy.slack.com/archives/CEFDKQ3RQ/p1588129018117000) (linked in #2479) it seems like the typed-config thing is only supported in v3.

**Comment by skriss** [comment]
@stevesloka I'm seeing this error in the Contour log when I test this change:
```
ERRO[0011] Error adding/updating listener(s) ingress_http: Compressor filter doesn't have compressor_library defined  code=13 connection=6 context=xds node_id=envoy-2s99g node_version=v1.15.0 response_nonce=1 version_info=2
```

**Comment by stevesloka** [comment]
Closing this since the typed config isn't working with v2 xds types. Will come back when implementing v3 and I think it will work then avoiding this issue in the future.

**Pull request closed without merging**
