### PR TITLE
Changed targetPort for httpbin pods

### PR DESCRIPTION
**Pull request by JasonMorgan**
website: fixing https://projectcontour.io/examples/httpbin.yaml so that the service serves up the httpbin site.

Didn't bother making an issue but I'm happy to if that's useful.

The containers serve traffic at 80, not 8080. The service gives you 503s until you make this change.

Signed-off-by: Jason Morgan <jmorgan@pivotal.io>

### CODE REVIEW

**Comment by stevesloka** [comment]
@JasonMorgan could you sign the commit so we pass the DCO? 

```
 $ git commit --amend --signoff
```

**Comment by JasonMorgan** [comment]
Hey sorry, just seeing this, let me sign it appropriately, just did the old browser edit.

**Comment by stevesloka** [comment]
Hey @JasonMorgan friendly ping if you're available to sign off your commit. Thanks!

**Comment by JasonMorgan** [comment]
Sorry about the delay!

**Comment by stevesloka** [comment]
No worries, thanks @JasonMorgan!

**Pull request merged**
